const limits=new Map();
function send(res,status,payload){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}).end(JSON.stringify(payload));}
async function user(req,fetchImpl,env){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token||!env.SUPABASE_URL||!env.SUPABASE_PUBLISHABLE_KEY)return null;const response=await fetchImpl(`${env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}});return response.ok?response.json():null;}
function allowed(id,now=Date.now()){const rows=(limits.get(id)||[]).filter(time=>now-time<60000);if(rows.length>=20)return false;rows.push(now);limits.set(id,rows);return true;}
function abstractText(index){if(!index||typeof index!=='object')return '';return Object.entries(index).flatMap(([word,positions])=>(positions||[]).map(position=>[position,word])).sort((a,b)=>a[0]-b[0]).map(row=>row[1]).join(' ').slice(0,1800);}
function plainText(value){return String(value||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim().slice(0,1800);}
async function crossrefSearch({query,year,openAccess,fetchImpl}){
  const filters=[`from-pub-date:${year}-01-01`,'type:journal-article'];if(openAccess)filters.push('has-full-text:true');
  const params=new URLSearchParams({query,filter:filters.join(','),rows:'100',sort:'relevance',order:'desc',select:'DOI,title,author,published,container-title,URL,is-referenced-by-count,abstract,link'});
  const response=await fetchImpl(`https://api.crossref.org/works?${params}`,{headers:{'User-Agent':'FisioClinico/0.6 (busca educacional de literatura)'}}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||'As fontes científicas não responderam.');
  const items=payload.message?.items||[],results=items.map(work=>{const links=Array.isArray(work.link)?work.link:[],pdf=links.find(link=>/pdf/i.test(link['content-type']||'')||/\.pdf(?:$|\?)/i.test(link.URL||''))?.URL||'',doi=work.DOI?`https://doi.org/${work.DOI}`:'',date=work.published?.['date-parts']?.[0]||[];return {id:work.DOI||work.URL,title:work.title?.[0]||'Sem título',year:date[0]||'',date:date.length?`${date[0]}-${String(date[1]||1).padStart(2,'0')}-${String(date[2]||1).padStart(2,'0')}`:'',authors:(work.author||[]).slice(0,6).map(author=>[author.given,author.family].filter(Boolean).join(' ')),source:work['container-title']?.[0]||'',doi,url:doi||work.URL||'',pdfUrl:pdf,openAccess:Boolean(pdf),oaStatus:pdf?'texto completo informado pela fonte':'não verificado',citations:Number(work['is-referenced-by-count']||0),abstract:plainText(work.abstract)};});
  return {results,total:payload.message?.['total-results']||results.length,source:'Crossref'};
}
export async function handleArticleSearch(req,res,{fetchImpl=fetch,env=process.env}={}){
  if(req.method!=='GET'){send(res,405,{error:'Método não permitido.'});return;}
  try{const account=await user(req,fetchImpl,env);if(!account){send(res,401,{error:'Entre novamente para pesquisar artigos.'});return;}if(!allowed(account.id)){send(res,429,{error:'Muitas pesquisas. Aguarde um minuto.'});return;}
    const url=new URL(req.url,'http://localhost'),query=String(url.searchParams.get('q')||'').trim().slice(0,300),year=Math.max(1900,Math.min(new Date().getFullYear(),Number(url.searchParams.get('year'))||2015)),openAccess=url.searchParams.get('oa')==='1';if(query.length<3){send(res,400,{error:'Digite um tema com pelo menos três caracteres.'});return;}
    const filters=[`from_publication_date:${year}-01-01`,'type:article'];if(openAccess)filters.push('open_access.is_oa:true');const params=new URLSearchParams({search:query,filter:filters.join(','),sort:'relevance_score:desc',per_page:'100',select:'id,doi,display_name,publication_year,publication_date,type,cited_by_count,authorships,primary_location,open_access,best_oa_location,abstract_inverted_index'});if(env.OPENALEX_API_KEY)params.set('api_key',env.OPENALEX_API_KEY);
    const upstream=await fetchImpl(`https://api.openalex.org/works?${params}`,{headers:{'User-Agent':'FisioClinico/0.6 (busca educacional de literatura)'}});const payload=await upstream.json().catch(()=>({}));if(!upstream.ok){const fallback=await crossrefSearch({query,year,openAccess,fetchImpl});send(res,200,{query,year,...fallback});return;}
    const results=(payload.results||[]).map(work=>{const location=work.best_oa_location||work.primary_location||{},authors=(work.authorships||[]).slice(0,6).map(row=>row.author?.display_name).filter(Boolean);return {id:work.id,title:work.display_name||'Sem título',year:work.publication_year,date:work.publication_date||'',authors,source:location.source?.display_name||work.primary_location?.source?.display_name||'',doi:work.doi||'',url:location.landing_page_url||work.doi||work.id,pdfUrl:location.pdf_url||'',openAccess:Boolean(work.open_access?.is_oa),oaStatus:work.open_access?.oa_status||'',citations:Number(work.cited_by_count||0),abstract:abstractText(work.abstract_inverted_index)};});send(res,200,{query,year,total:payload.meta?.count||results.length,results,source:'OpenAlex'});
  }catch(error){send(res,error.statusCode||502,{error:error.message||'Falha ao pesquisar artigos.'});}
}
