const endpoint = process.argv[2];
if (!endpoint) throw new Error('Informe o endpoint WebSocket do Chrome DevTools.');
const socket = new WebSocket(endpoint);
await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});
let nextId=0;
const pending=new Map();
socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const item=pending.get(message.id);pending.delete(message.id);message.error?item.reject(new Error(message.error.message)):item.resolve(message.result);}});
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++nextId;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
await call('Page.enable');
await call('Runtime.enable');
await call('Page.navigate',{url:'http://localhost:4173/#inicio'});await wait(700);
await evaluate(`localStorage.setItem('fisio-clinico:v2', JSON.stringify({version:3,patients:[{id:'gait-qa',code:'P-MARCHA',focus:'Avaliação funcional',createdAt:new Date().toISOString()}],assessments:[],plans:[],sessions:[],exercises:[],favorites:[],repertoires:[],goniometryRecords:[],caseDiscussions:[]}))`);
await call('Page.reload');await wait(500);
await call('Page.navigate',{url:'http://localhost:4173/#pacientes/gait-qa/marcha'});await wait(500);
const hasButton=await evaluate(`Boolean(document.querySelector('[data-action="new-gait-assessment"]'))`);
if(!hasButton){const diagnostic=await evaluate(`({hash:location.hash,main:document.querySelector('#main')?.textContent?.slice(0,500),stored:localStorage.getItem('fisio-clinico:v2'),errors:window.__qaErrors||[]})`);throw new Error('Botão Avaliar marcha não encontrado: '+JSON.stringify(diagnostic));}
await evaluate(`document.querySelector('[data-action="new-gait-assessment"]').click()`);await wait(250);
const modal=await evaluate(`({title:document.querySelector('#modal-title')?.textContent,steps:document.querySelectorAll('.gait-step').length,tests:document.querySelectorAll('.gait-test').length})`);
if(modal.title!=='Avaliação guiada da marcha'||modal.steps!==5||modal.tests<6)throw new Error('Estrutura do assistente incompleta: '+JSON.stringify(modal));
await evaluate(`document.querySelector('[name="environment"]').value='Corredor plano, 10 m';document.querySelector('[name="device"]').value='Bengala habitual';document.querySelector('[name="pace"]').value='lento';document.querySelector('[name="symmetry"]').value='menor-esquerda';document.querySelector('[name="turn"]').value='passos-multiplos';document.querySelector('[name="selectedTest"][value="10mwt"]').checked=true;document.querySelector('[name="testResults"]').value='Protocolo registrado sem interpretação automática';document.querySelector('#gait-assessment-form').requestSubmit()`);await wait(450);
const saved=await evaluate(`JSON.parse(localStorage.getItem('fisio-clinico:v2')).assessments[0]`);
if(saved?.type!=='Marcha'||saved.gait?.selectedTests?.[0]!=='10mwt'||!saved.findings.includes('Passo menor à esquerda')||!saved.findings.includes('Teste de Caminhada de 10 Metros'))throw new Error('Persistência da marcha falhou: '+JSON.stringify(saved));
const card=await evaluate(`({badge:document.querySelector('.gait-entry .badge')?.textContent,summary:document.querySelector('.gait-entry p')?.textContent,tags:document.querySelectorAll('.gait-tags span').length})`);
if(card.badge!=='Marcha'||card.tags!==1||!card.summary.includes('Resumo observacional'))throw new Error('Cartão salvo incompleto: '+JSON.stringify(card));
await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await evaluate(`document.querySelector('[data-action="new-gait-assessment"]').click()`);await wait(250);
const mobile=await evaluate(`({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,modalWidth:document.querySelector('.gait-modal').getBoundingClientRect().width,viewport:innerWidth,columns:getComputedStyle(document.querySelector('.gait-tests')).gridTemplateColumns})`);
if(mobile.scroll>mobile.width+1||mobile.modalWidth>mobile.viewport+1||mobile.columns.split(' ').length!==1)throw new Error('Layout móvel da marcha falhou: '+JSON.stringify(mobile));
console.log(JSON.stringify({button:true,steps:modal.steps,testChoices:modal.tests,persistence:true,summary:true,mobile:true},null,2));
socket.close();
