const ENDPOINT='https://api.groq.com/openai/v1/chat/completions';
const limits=new Map();
function json(res,status,payload){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}).end(JSON.stringify(payload));}
async function body(req){if(req.body&&typeof req.body==='object')return req.body;const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>50000)throw Object.assign(new Error('Conteúdo muito grande.'),{statusCode:413});chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');}
async function user(req,fetchImpl,env){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;if(!env.SUPABASE_URL||!env.SUPABASE_PUBLISHABLE_KEY)throw Object.assign(new Error('Autenticação do servidor não configurada.'),{statusCode:503});const r=await fetchImpl(`${env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}});return r.ok?r.json():null;}
function allowed(id,now=Date.now()){const rows=(limits.get(id)||[]).filter(x=>now-x<60000);if(rows.length>=12)return false;rows.push(now);limits.set(id,rows);return true;}
const section={type:'object',properties:{title:{type:'string'},content:{type:'string'},items:{type:'array',items:{type:'string'}}},required:['title','content','items'],additionalProperties:false};
const schema={type:'object',properties:{title:{type:'string'},primaryOutput:{type:'string'},memory:{type:'string'},sections:{type:'array',items:section},questions:{type:'array',items:{type:'string'}},improvements:{type:'array',items:{type:'string'}},cautions:{type:'array',items:{type:'string'}},score:{type:'integer',minimum:0,maximum:100}},required:['title','primaryOutput','memory','sections','questions','improvements','cautions','score'],additionalProperties:false};
const shared=`Você é um professor de fisioterapia para um estagiário absolutamente iniciante. Responda em português brasileiro, com linguagem simples e tecnicamente cuidadosa. Use apenas fatos enviados. Nunca invente achados, diagnóstico, prognóstico, dose individual ou segurança. Diferencie o que foi informado, o que precisa ser perguntado ou medido e o que é apenas possibilidade para discutir com o supervisor. Não substitua avaliação presencial. Não dê autorização para atender. Dados de pacientes devem permanecer desidentificados. REGRA ABSOLUTA DE IDIOMA: todos os valores textuais do JSON devem estar exclusivamente em português brasileiro. Nunca use inglês em títulos, explicações, falas, feedbacks ou perguntas, mesmo que as propriedades do JSON tenham nomes em inglês.`;
export const normalizeLearningMode=mode=>({escrita:'writing',agora:'next',raciocinio:'reasoning','primeira-sessao':'session',tradutor:'translate'}[mode]||mode);
const prompts={
  writing:`Reescreva no formato solicitado sem acrescentar fatos. Em primaryOutput coloque o texto final. Em improvements explique objetivamente o que melhorou. Em questions liste dados ausentes que fariam diferença. Para SOAP, não invente itens de nenhuma seção.`,
  next:`Crie um roteiro passo a passo para a fase informada. Comece pelo essencial, diga o que perguntar/observar/medir, o que registrar e quando parar para chamar o supervisor. Não conclua diagnóstico.`,
  reasoning:`Explique o raciocínio por trás de cada possibilidade: por que considerar, que pergunta clínica responde e o que o resultado não permite concluir. Mostre alternativas e limites.`,
  session:`Monte uma estrutura conservadora de primeira sessão para discussão. Separe checagem inicial, preparação, atividade principal, função, pausas, resposta a monitorar e reavaliação. Não fixe dose como prescrição; use opções condicionais.`,
  translate:`Transforme a linguagem comum em alternativas de registro clínico objetivo. Não converta impressão em achado. Mostre frases possíveis e quais observações/medidas precisam confirmar cada uma.`,
  'simulation-start':`Crie um paciente fictício coerente com a área e dificuldade escolhidas. primaryOutput deve ser somente a fala inicial do paciente. Guarde todos os fatos do caso em memory. Não revele o caso completo nem dê feedback ainda.`,
  'simulation-reply':`Interprete somente o paciente fictício descrito em memory. Responda apenas ao que o aluno perguntou, como paciente leigo. primaryOutput é a fala do paciente. Não ensine e não revele informações não perguntadas, exceto se seria espontâneo e coerente. Preserve memory.`,
  'simulation-feedback':`Encerre a simulação e avalie a entrevista. Mostre o que o aluno perguntou bem, o que esqueceu, perguntas de segurança, como organizaria a escrita e próximos estudos. Use score como desempenho educacional.`,
  'exam-generate':`Crie um caso curto de prova prática no nível informado. primaryOutput contém o caso e as tarefas do aluno: o que avaliar, riscos, documentação e discussão de conduta. Guarde o gabarito detalhado em memory e não o revele.`,
  'exam-grade':`Compare a resposta do aluno com o gabarito em memory. Dê pontuação educacional de 0 a 100, acertos, lacunas, riscos esquecidos, exemplo de resposta melhor e temas para revisar.`
};
export async function handleLearningTool(req,res,{fetchImpl=fetch,env=process.env}={}){
  if(req.method!=='POST'){json(res,405,{error:'Método não permitido.'});return;}
  try{const account=await user(req,fetchImpl,env);if(!account){json(res,401,{error:'Entre novamente para usar esta ferramenta.'});return;}if(!allowed(account.id)){json(res,429,{error:'Muitas solicitações. Aguarde um minuto.'});return;}if(!env.GROQ_API_KEY){json(res,503,{error:'IA não configurada no servidor.'});return;}
    const data=await body(req),mode=normalizeLearningMode(String(data.mode||'')),instruction=prompts[mode];if(!instruction){json(res,400,{error:'Ferramenta desconhecida.'});return;}const input=String(data.input||'').trim().slice(0,14000),memory=String(data.memory||'').slice(0,10000),history=Array.isArray(data.history)?data.history.slice(-16):[];if(input.length<3&&![ 'simulation-feedback'].includes(mode)){json(res,400,{error:'Preencha as informações da atividade.'});return;}
    const conversation=history.map(row=>({role:row.role==='assistant'?'assistant':'user',content:String(row.content||'').slice(0,2000)}));const upstream=await fetchImpl(ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:env.GROQ_CLINICAL_MODEL||'openai/gpt-oss-120b',temperature:mode.startsWith('simulation')?.35:.15,max_completion_tokens:4500,messages:[{role:'system',content:`${shared}\n\nTAREFA:\n${instruction}\n\nA saída deve obedecer ao JSON solicitado.`},...conversation,{role:'user',content:`ENTRADA:\n${input||'Encerrar e avaliar.'}\n\nMEMÓRIA INTERNA DO CASO:\n${memory||'Ainda não existe.'}`}],response_format:{type:'json_schema',json_schema:{name:'learning_tool_response',strict:true,schema}}})});const payload=await upstream.json().catch(()=>({}));if(!upstream.ok){json(res,upstream.status===401?503:502,{error:upstream.status===401?'A chave da Groq foi recusada.':'Não foi possível gerar a atividade agora.'});return;}const raw=payload.choices?.[0]?.message?.content,result=typeof raw==='string'?JSON.parse(raw):raw;if(!result?.title||!Array.isArray(result.sections))throw new Error('Resposta incompleta da IA.');json(res,200,{result});
  }catch(error){json(res,error.statusCode||502,{error:error.name==='SyntaxError'?'Resposta inválida da IA.':error.message||'Falha ao gerar atividade.'});}
}
