const endpoint=process.argv[2];
if(!endpoint)throw new Error('Informe o endpoint WebSocket do Chrome DevTools.');
const socket=new WebSocket(endpoint);
await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});
let nextId=0;const pending=new Map();
socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const item=pending.get(message.id);pending.delete(message.id);message.error?item.reject(new Error(message.error.message)):item.resolve(message.result);}});
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++nextId;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
await call('Page.enable');await call('Runtime.enable');
await call('Page.navigate',{url:'http://localhost:4173/#inicio'});await wait(600);
await evaluate(`localStorage.setItem('fisio-clinico:v2',JSON.stringify({version:4,patients:[{id:'clinical-qa',code:'P-CLINICO',name:'Paciente QA',createdAt:new Date().toISOString()}],assessments:[],plans:[],sessions:[],exercises:[],favorites:[],repertoires:[],goniometryRecords:[],caseDiscussions:[]}))`);
await call('Page.reload');await wait(450);
await call('Page.navigate',{url:'http://localhost:4173/#pacientes/clinical-qa/avaliacao'});await wait(450);
await evaluate(`document.querySelector('[data-action="new-clinical-assessment"]').click()`);await wait(200);
await evaluate(`document.querySelector('[name="complaint"]').value='Dificuldade funcional';document.querySelector('[name="bp"]').value='120/80';document.querySelector('[name="pain"]').value='6';document.querySelector('[name="strengthMovement"]').value='Extensão de joelho';document.querySelector('[name="strengthGrade"]').value='3';document.querySelector('[name="romJoint"]').value='Joelho';document.querySelector('[name="romMovement"]').value='Flexão';document.querySelector('[name="romDegrees"]').value='90';document.querySelector('#clinical-assessment-form').requestSubmit()`);await wait(400);
let stored=await evaluate(`JSON.parse(localStorage.getItem('fisio-clinico:v2'))`);
if(stored.assessments.length!==1||stored.assessments[0].clinical.strength[0].grade!=='3'||stored.assessments[0].clinical.rom[0].degrees!=='90')throw new Error('Avaliação estruturada não persistiu corretamente.');
await call('Page.navigate',{url:'http://localhost:4173/#pacientes/clinical-qa/goniometria'});await wait(350);
await evaluate(`document.querySelector('[data-action="new-patient-gonio"]').click()`);await wait(150);
await evaluate(`document.querySelector('[name="value"]').value='95';document.querySelector('#patient-goniometry-form').requestSubmit()`);await wait(350);
stored=await evaluate(`JSON.parse(localStorage.getItem('fisio-clinico:v2'))`);
if(stored.goniometryRecords[0]?.patientId!=='clinical-qa'||stored.goniometryRecords[0]?.value!=='95')throw new Error('Goniometria não foi associada ao paciente.');
await call('Page.navigate',{url:'http://localhost:4173/#pacientes/clinical-qa/plano'});await wait(350);
await evaluate(`document.querySelector('[data-action="new-plan"]').click()`);await wait(150);
await evaluate(`document.querySelector('[name="title"]').value='Plano inicial';document.querySelector('[name="shortGoals"]').value='Reduzir dor';document.querySelector('#plan-form').requestSubmit()`);await wait(350);
stored=await evaluate(`JSON.parse(localStorage.getItem('fisio-clinico:v2'))`);
if(stored.plans[0]?.title!=='Plano inicial')throw new Error('Plano não foi persistido.');
await call('Page.navigate',{url:'http://localhost:4173/#imprimir/clinical-qa/avaliacao'});await wait(350);
const print=await evaluate(`({title:document.querySelector('.print-page h1')?.textContent,text:document.querySelector('.print-page')?.textContent})`);
if(!print.title||!print.text.includes('120/80')||!print.text.includes('95'))throw new Error('Rota de impressão da avaliação incompleta: '+JSON.stringify(print));
console.log(JSON.stringify({patientTabs:true,structuredAssessment:true,patientGoniometry:true,plan:true,print:true},null,2));
socket.close();
