const AUTHOR_SOURCE = 'Conteúdo educacional original do Fisio Clínico (2026), baseado em princípios gerais de cinesiologia e prática fisioterapêutica; revisar com supervisor e referências institucionais.';
const WHO_SOURCE = 'OMS — Rehabilitation (2024): reabilitação centrada na pessoa, em seus objetivos e funcionalidade.';
const LOW_BACK_SOURCE = 'OMS — Guideline for non-surgical management of chronic primary low back pain in adults (2023), https://www.who.int/publications/i/item/9789240081789.';
const CARDIOPULM_SOURCE = 'OMS — Package of interventions for rehabilitation, Module 4: Cardiopulmonary conditions (2023), https://www.who.int/publications/i/item/9789240071162.';

const presets = {
  Quadril:{region:'Quadril e pelve',joint:'Quadril',aux:'adutores, musculatura do core e estabilizadores pélvicos',capacity:'força, controle lumbopélvico e função dos membros inferiores',progression:'Aumentar amplitude, resistência ou demanda unilateral somente mantendo controle e tolerância.',regression:'Reduzir amplitude ou resistência; ampliar apoio e usar assistência manual quando necessário.',compensation:'Inclinação ou rotação do tronco, perda do alinhamento pélvico e uso de impulso.'},
  Joelho:{region:'Joelho e membro inferior',joint:'Joelho',aux:'glúteos, isquiotibiais, panturrilha e estabilizadores do tronco',capacity:'força, controle do joelho e tarefas de suporte de peso',progression:'Aumentar gradualmente amplitude, resistência, altura ou complexidade da tarefa.',regression:'Diminuir amplitude/carga, elevar o assento ou acrescentar apoio dos membros superiores.',compensation:'Valgo ou varo não controlado, descarga assimétrica e excesso de impulso.'},
  'Tornozelo e pé':{region:'Tornozelo e pé',joint:'Tornozelo e articulações do pé',aux:'musculatura intrínseca do pé, fibulares e estabilizadores proximais',capacity:'mobilidade, força distal, controle postural e propulsão',progression:'Progredir resistência, apoio unilateral ou desafio da superfície de forma supervisionada.',regression:'Executar sentado, com apoio manual ou em menor amplitude.',compensation:'Rotação do membro, flexão dos dedos, perda do arco ou uso excessivo do tronco.'},
  Ombro:{region:'Cintura escapular e ombro',joint:'Complexo do ombro',aux:'trapézio, serrátil anterior, deltoide e musculatura do tronco',capacity:'mobilidade, controle escapular e força do membro superior',progression:'Ampliar alcance ou resistência sem perder ritmo escapular e conforto.',regression:'Usar assistência do membro oposto, apoio do antebraço ou menor amplitude.',compensation:'Elevação do ombro, extensão lombar, projeção anterior da cabeça e movimento brusco.'},
  'Cotovelo, punho e mão':{region:'Membro superior distal',joint:'Cotovelo, antebraço, punho ou dedos',aux:'estabilizadores do ombro e musculatura intrínseca da mão',capacity:'mobilidade, força de preensão e função manual',progression:'Aumentar resistência, precisão, velocidade ou complexidade funcional.',regression:'Reduzir resistência, apoiar o antebraço ou usar objetos maiores e leves.',compensation:'Elevação do ombro, desvio do punho, preensão excessiva e uso de impulso.'},
  Coluna:{region:'Coluna e tronco',joint:'Segmentos da coluna e pelve',aux:'multífidos, diafragma, glúteos e musculatura estabilizadora',capacity:'mobilidade, controle motor, resistência e estabilidade do tronco',progression:'Aumentar alavanca, tempo, amplitude ou reduzir base de apoio mantendo respiração e controle.',regression:'Diminuir alavanca/amplitude, usar apoio ou escolher posição mais estável.',compensation:'Prender a respiração, perder posição confortável ou transferir movimento para segmentos adjacentes.'},
  Equilíbrio:{region:'Corpo inteiro',joint:'Múltiplas articulações',aux:'estratégias de tornozelo, quadril, passo e controle do tronco',capacity:'controle postural, orientação e ajustes antecipatórios/reativos',progression:'Reduzir apoio ou pistas, variar superfície e adicionar alcance ou tarefa secundária.',regression:'Ampliar base, manter apoio próximo e oferecer supervisão ou assistência compatível.',compensation:'Fixação excessiva, passos sem controle, apoio intenso e estratégia insegura.'},
  Marcha:{region:'Corpo inteiro',joint:'Quadril, joelho, tornozelo e tronco',aux:'estabilizadores pélvicos, musculatura do core e membros superiores',capacity:'locomoção, transferência de peso, ritmo e adaptação da marcha',progression:'Variar velocidade, direção, distância e ambiente mantendo segurança.',regression:'Reduzir percurso/velocidade, retirar obstáculos e usar dispositivo ou assistência prescrita.',compensation:'Passos assimétricos, arrasto, inclinação excessiva e dependência inadequada do apoio.'},
  Neuro:{region:'Controle motor e função',joint:'Conforme a tarefa',aux:'cadeias musculares envolvidas na tarefa e controle postural',capacity:'aprendizagem motora, controle postural, coordenação e tarefa funcional',progression:'Reduzir ajuda ou pistas e aumentar variabilidade/complexidade somente com desempenho seguro.',regression:'Simplificar a tarefa, aumentar apoio, segmentar etapas e oferecer pistas ou assistência.',compensation:'Estratégias associadas que reduzem eficiência ou segurança da tarefa.'},
  Pediatria:{region:'Desenvolvimento motor global',joint:'Múltiplas articulações',aux:'musculatura postural e grupos envolvidos na brincadeira',capacity:'motricidade grossa, exploração, coordenação e participação',progression:'Variar brinquedo, direção, distância ou superfície conforme resposta e interesse da criança.',regression:'Aproximar alvo, aumentar apoio e facilitar uma etapa da transição.',compensation:'Evitar uma direção, depender de apoio, perder alinhamento ou abandonar a tarefa.'}
};

const dose = {
  força:'Exemplo educacional: 2–3 séries de 6–12 repetições, com resistência e intervalo definidos pela avaliação de força, objetivo e resposta.',
  mobilidade:'Exemplo educacional: 1–3 séries de 6–10 movimentos lentos ou permanências breves, dentro da amplitude avaliada como adequada.',
  equilíbrio:'Exemplo educacional: 3–5 tentativas de 20–40 segundos, com apoio e supervisão ajustados ao risco e à qualidade.',
  marcha:'Exemplo educacional: blocos de 2–5 minutos ou percursos curtos, com pausas e assistência conforme fadiga e segurança.',
  motor:'Exemplo educacional: 5–10 tentativas orientadas à tarefa, priorizando qualidade, participação e descanso.',
  função:'Exemplo educacional: 2–4 blocos de 4–8 repetições da tarefa, adaptados à capacidade e relevância funcional.'
};

const rows = {
Quadril:[
['Ponte de quadril','ponte de glúteos','Extensão de quadril','glúteo máximo; isquiotibiais','Decúbito dorsal, joelhos flexionados e pés apoiados.','Organizar pelve, pressionar os pés e elevar o quadril; sustentar controle; retornar lentamente.','Treinar extensão de quadril e controle lumbopélvico.','Transferências no leito, levantar e estabilidade pélvica.','colchonete','Básica','força','ponte glúteos extensão','levantar cadeira|subir escada'],
['Ponte unilateral','ponte com uma perna','Extensão de quadril','glúteo máximo; isquiotibiais','Decúbito dorsal com um pé apoiado e o outro membro organizado sem apoio.','Estabilizar a pelve; elevar com o membro apoiado; evitar rotação; descer com controle.','Aumentar demanda unilateral de extensores e estabilizadores pélvicos.','Controle pélvico na marcha e tarefas assimétricas.','colchonete','Intermediária','força','ponte unilateral glúteo','subir escada'],
['Clam shell','concha','Abdução e rotação externa','glúteo médio; rotadores laterais do quadril','Decúbito lateral, quadris e joelhos flexionados, pés juntos.','Manter pelve empilhada; separar o joelho superior sem girar o tronco; retornar lentamente.','Treinar controle lateral do quadril.','Estabilidade pélvica no apoio unilateral e marcha.','miniband opcional','Básica','força','clam concha glúteo médio','equilíbrio|marcha lateral'],
['Abdução de quadril em decúbito lateral','elevação lateral da perna','Abdução','glúteo médio','Decúbito lateral, membro inferior de baixo flexionado e superior alinhado.','Alongar o membro superior; elevar sem rodar a pelve; pausar; retornar com controle.','Fortalecer abdutores do quadril.','Controle pélvico durante marcha, degraus e apoio unilateral.','tornozeleira opcional','Básica','força','abdução lateral glúteo médio','equilíbrio|subir escada'],
['Extensão de quadril em pé','coice de quadril','Extensão','glúteo máximo; isquiotibiais','Ortostatismo com apoio estável.','Manter tronco ereto; levar a coxa para trás sem arquear a lombar; retornar.','Treinar extensão de quadril em cadeia aberta.','Fase de apoio terminal e tarefas de propulsão.','faixa elástica opcional','Básica','força','extensão quadril em pé','marcha|subir escada'],
['Flexão de quadril em pé','marcha estacionária','Flexão','iliopsoas; reto femoral','Ortostatismo com apoio disponível.','Elevar um joelho até a amplitude controlada; manter pelve estável; retornar e alternar.','Treinar flexores do quadril e controle em apoio.','Avanço do membro na marcha e transposição de obstáculos.','apoio estável','Básica','motor','flexão marcha iliopsoas','marcha|obstáculos'],
['Marcha com resistência elástica','marcha resistida','Flexão e extensão','iliopsoas; glúteo máximo','Ortostatismo com faixa posicionada e ponto de apoio seguro.','Organizar tronco; alternar passos contra resistência leve; manter ritmo e alinhamento.','Integrar força de quadril ao padrão de marcha.','Locomoção e controle de passos.','faixa elástica','Intermediária','marcha','marcha resistência quadril','marcha|subir escada'],
['Caminhada lateral','passos laterais','Abdução e adução','glúteo médio; adutores','Ortostatismo, base confortável e apoio próximo.','Deslocar um pé lateralmente; transferir peso; aproximar o outro sem arrastar.','Treinar deslocamento lateral e estabilidade pélvica.','Mudanças laterais e circulação em espaços reduzidos.','faixa opcional','Básica','marcha','caminhada lateral glúteo médio','equilíbrio|marcha lateral'],
['Monster walk','caminhada diagonal com faixa','Abdução e extensão','glúteo médio; glúteo máximo','Semiagachamento leve com faixa e apoio acessível.','Manter tensão confortável; dar passos diagonais curtos; controlar joelhos e pelve.','Aumentar demanda dos estabilizadores do quadril em deslocamento.','Controle dos membros inferiores em tarefas multidirecionais.','miniband','Intermediária','força','monster walk faixa quadril','equilíbrio|subir escada'],
['Step-up baixo','subida no degrau','Extensão de quadril e joelho','glúteo máximo; quadríceps','Em frente a degrau baixo, apoio seguro próximo.','Apoiar todo o pé; transferir peso; subir controlando joelho e pelve; descer.','Treinar força e controle na subida.','Subir degraus e transpor desníveis.','degrau; corrimão','Intermediária','função','step up degrau quadril','subir escada|levantar cadeira'],
['Step-down controlado','descida do degrau','Flexão controlada de quadril e joelho','glúteo médio; quadríceps','Sobre degrau baixo, um pé próximo à borda.','Flexionar o membro de apoio; aproximar o calcanhar oposto do solo; retornar.','Treinar controle excêntrico e alinhamento.','Descer escadas e controlar o centro de massa.','degrau; apoio','Intermediária','função','step down quadril','descer escada|equilíbrio'],
['Adução de quadril com bola','aperto de bola','Adução','adutores do quadril','Sentado ou em decúbito, bola macia entre os joelhos.','Organizar pelve; comprimir suavemente a bola; relaxar sem perder posição.','Treinar recrutamento dos adutores.','Controle medial dos membros e estabilidade em transferências.','bola macia','Básica','força','adução adutores bola','levantar cadeira'] ],
Joelho:[
['Extensão de joelho sentada','cadeira extensora sem máquina','Extensão','quadríceps','Sentado, coxa apoiada e pés livres.','Estender o joelho na amplitude selecionada; pausar; retornar lentamente.','Treinar quadríceps em cadeia aberta.','Controle do joelho em marcha, transferências e escadas.','tornozeleira opcional','Básica','força','extensão joelho quadríceps','levantar cadeira|subir escada'],
['Extensão terminal de joelho','TKE','Extensão terminal','quadríceps','Em pé com faixa atrás do joelho e apoio seguro.','Partir com leve flexão; estender contra a faixa sem mover o quadril; retornar.','Treinar controle da extensão final em apoio.','Estabilidade do joelho durante apoio e marcha.','faixa elástica','Básica','força','TKE extensão terminal','marcha|subir escada'],
['Agachamento','squat','Flexão e extensão','quadríceps; glúteo máximo','Em pé, pés em base avaliada e apoio disponível.','Levar quadril para trás e flexionar joelhos; manter pés apoiados; retornar estendendo quadril e joelhos.','Treinar força global dos membros inferiores e controle de tronco.','Levantar, agachar e manejar objetos em níveis baixos.','cadeira opcional','Intermediária','força','agachamento quadríceps glúteo','levantar cadeira|subir escada'],
['Miniagachamento com apoio','agachamento parcial','Flexão e extensão parcial','quadríceps; glúteo máximo','Em pé diante de apoio firme.','Flexionar pouco quadris e joelhos; manter alinhamento; retornar usando o mínimo apoio necessário.','Introduzir suporte de peso e controle dos membros inferiores.','Preparação para sentar, levantar e agachar.','barra ou bancada','Básica','função','mini agachamento apoio','levantar cadeira|equilíbrio'],
['Wall sit','agachamento isométrico na parede','Flexão mantida','quadríceps; glúteo máximo','Costas apoiadas na parede, pés à frente.','Deslizar até ângulo confortável; manter apoio e respiração; subir para encerrar.','Treinar resistência isométrica dos membros inferiores.','Sustentar posturas semiflexionadas.','parede','Intermediária','força','wall sit isométrico','levantar cadeira|subir escada'],
['Sentar e levantar','sit-to-stand','Extensão de joelho e quadril','quadríceps; glúteo máximo','Sentado na borda, pés organizados no solo.','Inclinar o tronco à frente; transferir peso aos pés; levantar; sentar controlando a descida.','Treinar uma transferência funcional essencial.','Independência ao usar cadeira, cama e vaso sanitário.','cadeira','Básica','função','sentar levantar transferência','levantar cadeira|subir escada'],
['Elevação da perna estendida','straight leg raise; SLR ativo','Flexão de quadril com joelho estendido','quadríceps; iliopsoas','Decúbito dorsal, um joelho flexionado e outro estendido.','Ativar quadríceps; elevar o membro estendido sem perder controle pélvico; retornar.','Treinar manutenção da extensão do joelho durante elevação do membro.','Controle do membro no leito e preparação para mobilidade.','colchonete','Básica','força','SLR perna estendida quadríceps','transferência leito'],
['Deslizamento de calcanhar','heel slide','Flexão e extensão','isquiotibiais; quadríceps','Decúbito dorsal com pernas apoiadas.','Deslizar o calcanhar aproximando-o do quadril; respeitar amplitude; retornar.','Explorar mobilidade ativa do joelho.','Ajustar o membro no leito e preparar transferências.','toalha opcional','Básica','mobilidade','heel slide flexão joelho','mobilidade joelho'],
['Flexão de joelho em pé','hamstring curl','Flexão','isquiotibiais','Em pé com apoio estável.','Dobrar o joelho levando o calcanhar para trás; manter coxas alinhadas; retornar.','Treinar flexores do joelho.','Controle do membro na marcha e atividades em pé.','tornozeleira opcional','Básica','força','flexão joelho isquiotibiais','marcha'],
['Avanço curto','afundo assistido; lunge curto','Flexão e extensão','quadríceps; glúteo máximo','Base anteroposterior curta com apoio próximo.','Distribuir peso; flexionar ambos os membros na amplitude segura; retornar.','Treinar força e controle em base assimétrica.','Dar passos, recuperar equilíbrio e subir desníveis.','apoio opcional','Intermediária','força','avanço afundo joelho','subir escada|equilíbrio'],
['Toque do calcanhar no alvo','heel tap','Flexão controlada','quadríceps; glúteo médio','Em pé sobre base baixa, apoio disponível.','Flexionar o membro de apoio e tocar o calcanhar livre em alvo; retornar sem colapsar o joelho.','Treinar controle excêntrico em apoio unilateral.','Descida de degraus e desaceleração.','degrau baixo','Intermediária','função','heel tap controle joelho','descer escada'],
['Agachar e alcançar objeto','agachamento funcional','Flexão e extensão','quadríceps; glúteo máximo','Em pé diante de objeto leve em altura ajustável.','Aproximar-se; agachar com controle; alcançar; retornar mantendo o objeto próximo.','Integrar membros inferiores e tronco em tarefa relevante.','Pegar e colocar objetos em níveis baixos.','objeto leve; alvo','Intermediária','função','agachar alcançar funcional','levantar objeto'] ],
'Tornozelo e pé':[
['Dorsiflexão com faixa','puxar a ponta do pé','Dorsiflexão','tibial anterior','Sentado, calcanhar apoiado e faixa fixada à frente.','Puxar o antepé em direção à perna; manter calcanhar; retornar lentamente.','Treinar dorsiflexores.','Liberação do pé durante a fase de balanço da marcha.','faixa elástica','Básica','força','dorsiflexão tibial anterior','marcha|pé arrastando'],
['Flexão plantar com faixa','empurrar o pé','Flexão plantar','gastrocnêmio; sóleo','Sentado, joelho confortável e faixa no antepé.','Apontar o pé contra a faixa sem girá-lo; retornar controladamente.','Treinar flexores plantares sem suporte de peso.','Propulsão na marcha e controle do tornozelo.','faixa elástica','Básica','força','flexão plantar panturrilha','marcha|subir escada'],
['Elevação bilateral de panturrilha','calf raise','Flexão plantar','gastrocnêmio; sóleo','Em pé com mãos próximas a apoio firme.','Elevar calcanhares; manter peso distribuído; pausar; descer lentamente.','Treinar panturrilha em suporte de peso.','Propulsão, alcance alto e subir degraus.','apoio estável','Básica','força','panturrilha calf raise','subir escada|marcha'],
['Elevação unilateral de panturrilha','calf raise unilateral','Flexão plantar','gastrocnêmio; sóleo','Apoio unipodal com suporte das mãos conforme necessidade.','Elevar o calcanhar do membro de apoio; manter alinhamento; descer controlando.','Aumentar demanda unilateral da panturrilha.','Propulsão e controle no apoio simples.','apoio estável','Avançada','força','panturrilha unilateral','marcha|subir escada'],
['Mobilidade de tornozelo joelho à parede','knee-to-wall','Dorsiflexão','sóleo; estruturas articulares do tornozelo','Em pé diante da parede, pé totalmente apoiado.','Levar o joelho em direção à parede sem elevar o calcanhar; retornar.','Explorar dorsiflexão em cadeia fechada.','Agachar, avançar e descer degraus.','parede','Básica','mobilidade','mobilidade tornozelo parede','agachar|descer escada'],
['Inversão com faixa','virar a planta para dentro','Inversão','tibial posterior; tibial anterior','Sentado, perna estável e faixa posicionada lateralmente.','Mover o antepé para dentro sem girar o joelho; retornar.','Treinar controle dos inversores.','Controle do pé durante apoio e adaptação ao solo.','faixa elástica','Básica','força','inversão tornozelo','equilíbrio'],
['Eversão com faixa','virar a planta para fora','Eversão','fibulares','Sentado, perna estável e faixa posicionada medialmente.','Mover o antepé para fora sem rodar a perna; retornar.','Treinar controle dos eversores.','Estabilidade lateral do tornozelo no apoio.','faixa elástica','Básica','força','eversão fibulares','equilíbrio'],
['Apoio unipodal estável','ficar em um pé','Estabilização','intrínsecos do pé; glúteo médio','Em pé ao lado de apoio firme.','Transferir peso; elevar um pé; manter postura e respiração; apoiar para encerrar.','Treinar controle postural sobre um membro.','Marcha, vestir-se e transpor degraus.','apoio estável','Intermediária','equilíbrio','unipodal propriocepção','equilíbrio|subir escada'],
['Elevação dos dedos e arco do pé','short foot combinado','Extensão dos dedos e controle do arco','tibial anterior; intrínsecos do pé','Sentado ou em pé, planta do pé apoiada.','Elevar os dedos; apoiar; aproximar suavemente a base do hálux do calcanhar sem enrolar dedos.','Explorar controle ativo do pé e tornozelo.','Estabilidade do apoio plantar.','nenhum','Básica','motor','pé arco dedos intrínsecos','equilíbrio'],
['Transferência do centro de pressão','balanço do tornozelo','Controle em dorsiflexão e flexão plantar','sóleo; tibial anterior','Em pé, base confortável e apoio disponível.','Mover o corpo levemente para frente e trás sem tirar os pés do chão; retornar ao centro.','Treinar estratégia de tornozelo.','Ajustes posturais durante espera e marcha.','apoio próximo','Básica','equilíbrio','tornozelo centro pressão','equilíbrio'] ],
Ombro:[
['Pêndulo de ombro','Codman','Movimentos passivos/assistidos multidirecionais','deltoide com baixa ativação; musculatura escapular','Tronco inclinado com mão oposta apoiada e braço relaxado.','Deixar o braço relaxado; produzir pequenos movimentos pelo deslocamento do corpo; reduzir até parar.','Promover movimento suave com baixa demanda ativa.','Higiene, vestir-se e preparação para alcance conforme fase clínica.','mesa ou apoio','Básica','mobilidade','pêndulo Codman ombro','mobilidade ombro'],
['Flexão ativa do ombro','elevação anterior','Flexão','deltoide anterior; serrátil anterior','Sentado ou em pé, braço ao lado do corpo.','Elevar o braço à frente na amplitude controlada; evitar compensar; retornar lentamente.','Treinar elevação ativa do membro superior.','Alcançar prateleiras e cuidados pessoais.','peso leve opcional','Básica','mobilidade','flexão ativa ombro deltoide','alcançar alto'],
['Flexão assistida com bastão','elevação assistida','Flexão assistida','deltoide anterior; serrátil anterior','Decúbito ou sentado, mãos segurando bastão.','O membro menos limitado auxilia a elevar o outro; pausar; retornar de forma confortável.','Facilitar amplitude com assistência do membro oposto.','Preparação para alcance acima da cintura.','bastão','Básica','mobilidade','flexão assistida bastão','mobilidade ombro|alcançar alto'],
['Abdução ativa do ombro','elevação lateral','Abdução','deltoide médio; supraespinal','Em pé ou sentado, braço ao lado.','Elevar lateralmente no plano selecionado; manter pescoço relaxado; retornar.','Treinar elevação lateral e controle escapuloumeral.','Vestir camiseta e alcançar lateralmente.','peso leve opcional','Básica','mobilidade','abdução deltoide supraespinal','alcançar alto'],
['Rotação externa com faixa','rotação lateral resistida','Rotação externa','infraespinal; redondo menor','Em pé, cotovelo junto ao corpo e faixa presa medialmente.','Manter cotovelo estável; girar o antebraço para fora; retornar lentamente.','Treinar rotadores externos e controle do ombro.','Posicionar a mão e controlar tarefas de alcance.','faixa elástica','Básica','força','rotação externa manguito infraespinal','ombro controle'],
['Rotação interna com faixa','rotação medial resistida','Rotação interna','subescapular; peitoral maior','Em pé, cotovelo junto ao corpo e faixa presa lateralmente.','Puxar o antebraço para dentro sem mover o cotovelo; retornar.','Treinar rotadores internos em amplitude controlada.','Aproximar objetos do corpo e tarefas de autocuidado.','faixa elástica','Básica','força','rotação interna subescapular','ombro controle'],
['Retração escapular','aproximar escápulas','Retração','trapézio médio; romboides','Sentado ou em pé com braços relaxados.','Alongar a coluna; aproximar suavemente as escápulas sem elevar ombros; liberar.','Treinar consciência e controle escapular.','Organização da cintura escapular em alcance e postura.','nenhum','Básica','motor','retração escapular trapézio','postura|ombro controle'],
['Wall slide de ombro','deslizamento na parede','Flexão com rotação superior escapular','serrátil anterior; trapézio','Antebraços apoiados na parede e pés estáveis.','Deslizar os antebraços para cima; manter contato e controle do tronco; retornar.','Integrar elevação do braço e movimento escapular.','Alcance acima da cabeça.','parede; toalha opcional','Intermediária','motor','wall slide serrátil trapézio','alcançar alto'],
['Soco do serrátil em decúbito','serratus punch','Protração escapular','serrátil anterior','Decúbito dorsal, ombro flexionado e braço apontado para o teto.','Alcançar o teto movendo a escápula sem dobrar o cotovelo; retornar sem deixar cair.','Treinar controle da protração escapular.','Estabilidade da escápula durante empurrar e alcançar.','peso leve opcional','Básica','força','serrátil punch escápula','empurrar|alcançar'],
['Elevação no plano da escápula','scaption','Elevação no plano escapular','deltoide; supraespinal','Em pé, braços cerca de 30° à frente do plano frontal.','Elevar na amplitude escolhida com polegares confortáveis; retornar lentamente.','Treinar elevação com controle escapular.','Alcance diagonal e tarefas acima da cintura.','peso leve opcional','Intermediária','força','scaption supraespinal deltoide','alcançar alto'],
['Remada com faixa','rowing elástico','Extensão do ombro e retração','trapézio médio; romboides; deltoide posterior','Sentado ou em pé, faixa fixada à frente.','Puxar cotovelos para trás; organizar escápulas; retornar controlando a faixa.','Treinar extensores do ombro e estabilizadores escapulares.','Puxar portas e objetos.','faixa elástica','Básica','força','remada escápula trapézio','puxar'],
['Rotação externa isométrica na parede','isometria do manguito','Rotação externa isométrica','infraespinal; redondo menor','Ao lado da parede, cotovelo flexionado e dorso da mão apoiado em toalha.','Pressionar suavemente sem gerar movimento; respirar; relaxar.','Introduzir carga isométrica aos rotadores externos.','Controle inicial do ombro para tarefas do braço.','parede; toalha','Básica','força','isometria manguito infraespinal','ombro controle'] ],
'Cotovelo, punho e mão':[
['Flexão de cotovelo com faixa','rosca de bíceps','Flexão','bíceps braquial; braquial','Sentado ou em pé, faixa sob o pé e braço ao lado.','Dobrar o cotovelo sem avançar o ombro; pausar; estender lentamente.','Treinar flexores do cotovelo.','Levar objetos à boca e carregar volumes leves.','faixa ou halter','Básica','força','bíceps flexão cotovelo','carregar|autocuidado'],
['Extensão de cotovelo com faixa','tríceps com faixa','Extensão','tríceps braquial','Em pé, faixa fixada e cotovelo flexionado.','Estender o cotovelo mantendo braço organizado; retornar sem perder controle.','Treinar extensores do cotovelo.','Empurrar, apoiar os braços e transferir-se.','faixa elástica','Básica','força','tríceps extensão cotovelo','empurrar|transferência'],
['Pronação e supinação com bastão','girar o antebraço','Pronação e supinação','pronadores; supinador; bíceps','Sentado, cotovelo junto ao corpo e bastão leve na mão.','Girar a palma para cima e para baixo sem afastar o cotovelo; retornar ao neutro.','Explorar mobilidade do antebraço.','Usar talheres, maçanetas e virar objetos.','bastão leve','Básica','mobilidade','pronação supinação antebraço','função manual'],
['Flexão de punho','curl de punho','Flexão','flexores do punho','Antebraço apoiado, mão fora da borda e palma para cima.','Mover a palma em direção ao antebraço; manter dedos relaxados; retornar.','Treinar flexores do punho.','Segurar e estabilizar objetos na mão.','halter leve opcional','Básica','força','flexores punho','preensão'],
['Extensão de punho','extensão resistida','Extensão','extensores do punho','Antebraço apoiado, palma para baixo e mão livre.','Elevar o dorso da mão sem tirar o antebraço; retornar lentamente.','Treinar extensores do punho.','Estabilizar o punho durante preensão e apoio.','halter leve opcional','Básica','força','extensores punho','preensão|apoio mão'],
['Desvios radial e ulnar','desvio lateral do punho','Desvio radial e ulnar','flexor e extensor radial; flexor e extensor ulnar','Antebraço apoiado com polegar para cima.','Mover a mão para um lado e outro em amplitude confortável; evitar girar o antebraço.','Explorar controle lateral do punho.','Manipular utensílios e ferramentas leves.','martelo leve opcional','Básica','mobilidade','desvio punho','função manual'],
['Apertar bola macia','preensão palmar','Flexão dos dedos','flexores dos dedos; intrínsecos da mão','Sentado, antebraço apoiado e bola na palma.','Fechar os dedos gradualmente; manter punho neutro; liberar completamente.','Treinar preensão e controle de força.','Segurar copos, talheres e objetos.','bola macia','Básica','força','preensão mão bola','preensão|função manual'],
['Pinça com prendedores','pinça polpa-polpa','Pinça dos dedos','tenar; primeiro interósseo; flexores dos dedos','Sentado diante de prendedores leves e recipiente.','Abrir o prendedor com pinça selecionada; mover ao alvo; soltar com precisão.','Treinar pinça, destreza e graduação de força.','Abotoar, manejar chaves e pequenos objetos.','prendedores; recipiente','Básica','motor','pinça destreza mão','função manual'],
['Oposição do polegar','toques dedo-polegar','Oposição','músculos tenares; interósseos','Antebraço apoiado e mão relaxada.','Tocar a ponta do polegar em cada dedo; abrir a mão entre toques; variar sequência.','Treinar mobilidade e coordenação digital.','Manipular moedas, botões e tela do celular.','nenhum','Básica','motor','oposição polegar coordenação','função manual'],
['Deslizamento tendíneo dos dedos','tendon gliding','Flexão segmentar dos dedos','flexores dos dedos; intrínsecos da mão','Antebraço apoiado, punho neutro e dedos estendidos.','Alternar mão aberta, gancho, punho reto e punho fechado conforme tolerância; retornar.','Explorar excursão tendínea e coordenação dos dedos.','Abrir e fechar a mão em tarefas finas.','nenhum','Básica','mobilidade','deslizamento tendíneo dedos','função manual'],
['Transferência de objetos entre recipientes','separação de objetos','Múltiplos movimentos','intrínsecos da mão; flexores e extensores do punho','Sentado com dois recipientes e objetos seguros.','Selecionar objeto; ajustar preensão; transportar; soltar no alvo sem derrubar.','Integrar alcance, preensão e liberação.','Organização de itens e tarefas domésticas.','recipientes; objetos','Básica','função','destreza transferência objetos','função manual|alcançar'],
['Apoio progressivo das mãos na mesa','descarga em membro superior','Extensão de cotovelo e punho','tríceps; estabilizadores do punho e ombro','Em pé ou sentado diante de mesa firme, mãos apoiadas.','Transferir parte do peso às mãos; manter alinhamento; retornar ao centro.','Treinar tolerância ao apoio e estabilidade proximal.','Apoiar-se para transferências e levantar de superfícies.','mesa firme','Intermediária','função','apoio mãos tríceps punho','transferência'] ],
Coluna:[
['Rotação cervical ativa','olhar para os lados','Rotação cervical','músculos cervicais profundos e superficiais','Sentado com tronco apoiado e cabeça alinhada.','Girar a cabeça lentamente para um lado; retornar ao centro; repetir para o outro.','Explorar mobilidade cervical ativa.','Olhar ao atravessar rua e orientar-se no ambiente.','cadeira','Básica','mobilidade','cervical rotação','mobilidade cervical'],
['Inclinação cervical ativa','orelha em direção ao ombro','Inclinação lateral cervical','escalenos; esternocleidomastoideo','Sentado, ombros relaxados.','Inclinar a cabeça sem rodar nem elevar o ombro; voltar ao centro; alternar.','Explorar movimento lateral cervical.','Orientação da cabeça e conforto em tarefas sentadas.','cadeira','Básica','mobilidade','cervical inclinação','mobilidade cervical'],
['Chin tuck','retração cervical; recolher o queixo','Flexão craniocervical e retração','flexores cervicais profundos','Decúbito ou sentado, olhar horizontal.','Alongar a nuca e recuar suavemente o queixo sem baixar a cabeça; relaxar.','Treinar controle craniocervical.','Organização da cabeça durante leitura e trabalho.','toalha opcional','Básica','motor','chin tuck cervical','postura'],
['Rotação torácica em quatro apoios','passar a mão por baixo','Rotação torácica','rotadores torácicos; oblíquos','Quatro apoios com mãos sob ombros.','Deslizar um braço por baixo do corpo; retornar e abrir em rotação; acompanhar com o olhar.','Explorar rotação torácica com base estável.','Girar o tronco para alcançar e mudar direção.','colchonete','Intermediária','mobilidade','torácica rotação','mobilidade tronco'],
['Extensão torácica na cadeira','abrir o peito no encosto','Extensão torácica','extensores torácicos','Sentado com encosto apoiando a região torácica.','Apoiar mãos na nuca; estender suavemente sobre o encosto; retornar sem forçar cervical.','Explorar extensão torácica segmentar.','Alcance alto e postura ereta.','cadeira','Básica','mobilidade','torácica extensão','postura|alcançar alto'],
['Cat-cow','gato-vaca','Flexão e extensão da coluna','eretores da coluna; abdominais','Quatro apoios, mãos e joelhos confortáveis.','Arredondar a coluna de modo gradual; inverter para extensão confortável; sincronizar com respiração.','Explorar mobilidade global e consciência do tronco.','Mudanças de postura e controle do tronco.','colchonete','Básica','mobilidade','cat cow coluna','mobilidade tronco'],
['Inclinação pélvica em decúbito','pelvic tilt','Movimento lumbopélvico','abdominais; extensores lombares','Decúbito dorsal, joelhos flexionados e pés apoiados.','Alternar suavemente retroversão e retorno ao neutro; manter respiração.','Treinar percepção e controle da pelve.','Ajustes posturais no leito e em transferências.','colchonete','Básica','motor','pelvic tilt pelve core','controle tronco'],
['Bird dog','extensão alternada em quatro apoios','Extensão de quadril e ombro','glúteo máximo; musculatura do core','Quatro apoios com coluna confortável.','Deslizar ou elevar braço e perna opostos; manter pelve; retornar e alternar.','Treinar controle cruzado e estabilidade do tronco.','Coordenação entre membros e estabilidade em tarefas.','colchonete','Intermediária','motor','bird dog core coordenação','controle tronco|coordenação'],
['Dead bug','alternância em decúbito','Controle de tronco com membros em movimento','musculatura do core; iliopsoas','Decúbito dorsal com quadris/joelhos organizados e braços elevados.','Mover braço e perna opostos na amplitude controlada; retornar; alternar sem perder respiração.','Treinar controle do tronco durante movimento dos membros.','Estabilidade lumbopélvica em tarefas de alcance e marcha.','colchonete','Intermediária','motor','dead bug core','controle tronco|coordenação'],
['Prancha inclinada','prancha na parede ou mesa','Estabilização global','musculatura do core; serrátil anterior','Mãos em parede ou mesa firme, corpo alinhado.','Organizar corpo em linha; empurrar o apoio; manter respiração; sair com um passo.','Treinar resistência do tronco com carga ajustável.','Estabilidade durante empurrar e tarefas em pé.','parede ou mesa','Básica','força','prancha core serrátil','controle tronco|empurrar'],
['Ponte com marcha alternada','marcha na ponte','Controle lumbopélvico','glúteo máximo; musculatura do core','Ponte baixa estável em decúbito dorsal.','Transferir peso entre pés; aliviar um pé brevemente; alternar sem inclinar a pelve.','Treinar controle pélvico sob carga alternada.','Estabilidade pélvica na marcha.','colchonete','Avançada','motor','ponte marcha core','marcha|controle tronco'],
['Alcance sentado com rotação','alcance diagonal de tronco','Rotação e controle de tronco','oblíquos; extensores do tronco','Sentado com pés apoiados e alvo lateral.','Alongar o tronco; alcançar o alvo com rotação controlada; retornar ao centro.','Integrar mobilidade, equilíbrio sentado e alcance.','Pegar objetos ao lado e vestir-se.','alvo ou objeto leve','Básica','função','alcance tronco rotação sentado','alcançar|controle tronco'] ],
Equilíbrio:[
['Base reduzida com apoio próximo','pés juntos','Controle postural','sóleo; glúteo médio','Em pé, pés aproximados e apoio firme ao alcance.','Ajustar a base; manter olhar e respiração; usar apoio se perder estabilidade.','Treinar estabilidade com base menor.','Permanecer em pé em espaços estreitos.','apoio estável','Básica','equilíbrio','base reduzida equilíbrio','equilíbrio'],
['Semi-tandem','um pé parcialmente à frente','Controle postural anteroposterior','sóleo; glúteo médio','Em pé com um pé ligeiramente à frente, apoio próximo.','Distribuir peso; manter alinhamento; trocar a posição dos pés após a tentativa.','Treinar equilíbrio em base assimétrica moderada.','Preparar posição de passo e marcha.','apoio próximo','Básica','equilíbrio','semi tandem equilíbrio','equilíbrio|marcha'],
['Tandem','pés em linha','Controle postural em base estreita','sóleo; glúteo médio','Em pé, um pé diretamente à frente do outro e apoio próximo.','Assumir a posição com segurança; sustentar; sair ampliando a base; inverter pés.','Aumentar desafio mediolateral.','Controle em passagens estreitas e posição de passo.','apoio próximo','Intermediária','equilíbrio','tandem equilíbrio','equilíbrio|marcha'],
['Apoio unipodal com toques','relógio com o pé','Estabilização e alcance','glúteo médio; intrínsecos do pé','Em pé sobre um membro, outro pé livre e apoio disponível.','Tocar alvos ao redor com o pé livre; retornar ao centro entre toques.','Integrar apoio unilateral e deslocamento controlado.','Vestir-se, virar e transpor obstáculos.','marcadores; apoio','Intermediária','equilíbrio','unipodal relógio','equilíbrio|obstáculos'],
['Equilíbrio em superfície de espuma','superfície macia','Ajustes posturais','estratégias de tornozelo e quadril','Em pé sobre espuma firme, com barras ou apoio e supervisão.','Subir com auxílio; estabilizar; manter tarefa simples; sair com assistência prevista.','Variar informação somatossensorial e ajustes posturais.','Adaptação a superfícies diferentes.','espuma; barras','Avançada','equilíbrio','espuma superfície equilíbrio','equilíbrio'],
['Alcance multidirecional em pé','alcance funcional','Deslocamento do centro de massa','glúteo médio; musculatura do core','Em pé, alvos ao redor e apoio disponível.','Alcançar um alvo sem mover os pés; retornar ao centro; variar direções dentro da base.','Treinar limites de estabilidade.','Pegar objetos em armários e bancadas.','alvos','Intermediária','equilíbrio','alcance equilíbrio','equilíbrio|alcançar'],
['Transferência de peso lateral','balanço lateral','Deslocamento mediolateral','glúteo médio; adutores','Em pé com base confortável e apoio próximo.','Levar o peso para um lado sem inclinar excessivamente o tronco; retornar e alternar.','Treinar descarga e aceitação de peso.','Preparação para passos laterais e transferências.','espelho opcional','Básica','motor','transferência peso lateral','equilíbrio|marcha'],
['Transferência de peso anteroposterior','balanço frente-trás','Deslocamento anteroposterior','sóleo; tibial anterior','Em pé com um pé à frente, apoio disponível.','Transferir peso entre os pés mantendo contato com o solo; trocar a base.','Treinar progressão do corpo entre os membros.','Início do passo e mudanças de direção.','apoio próximo','Básica','motor','transferência peso frente trás','equilíbrio|marcha'],
['Perturbações leves previsíveis','empurrões graduados supervisionados','Respostas posturais','estratégias de tornozelo, quadril e passo','Em pé ou sentado com proteção adequada e comando combinado.','Informar direção; aplicar contato leve e graduado; observar ajuste; permitir recuperação segura.','Explorar respostas posturais com alta supervisão.','Recuperação diante de pequenos desequilíbrios cotidianos.','cinto de marcha se indicado','Avançada','motor','perturbação reativo equilíbrio','equilíbrio'],
['Caminhada com alcance de alvos','equilíbrio dinâmico','Locomoção com mudança do centro de massa','glúteo médio; musculatura do core','Em pé no início de percurso livre e protegido.','Caminhar até alvos; tocar em alturas seguras; retomar marcha e parar sob comando.','Integrar marcha, alcance e ajustes posturais.','Circular e interagir com objetos no ambiente.','alvos; percurso','Intermediária','marcha','equilíbrio dinâmico alcance','equilíbrio|marcha|alcançar'] ],
Marcha:[
['Iniciação do passo','passo à frente e voltar','Transferência e avanço','iliopsoas; glúteo médio','Em pé com base confortável, apoio e alvo no chão.','Transferir peso; levar um pé ao alvo; aceitar peso se planejado; retornar.','Treinar preparação e início do passo.','Começar a caminhar e transpor espaços.','marcador; apoio','Básica','motor','passo marcha iniciação','marcha'],
['Passos sobre marcas no solo','stepping em alvos','Avanço dos membros','iliopsoas; tibial anterior','Diante de sequência de marcas, assistência definida.','Avançar um pé por vez até as marcas; ajustar comprimento; parar com estabilidade.','Treinar comprimento e posicionamento do passo.','Regular passos em ambientes domésticos.','marcas no chão','Básica','marcha','passos alvos marcha','marcha'],
['Marcha sobre obstáculos baixos','circuito de obstáculos','Flexão de quadril/joelho e dorsiflexão','iliopsoas; quadríceps; tibial anterior','Diante de obstáculos baixos estáveis, ambiente protegido.','Aproximar; elevar o membro; ultrapassar sem tocar; reorganizar base antes do próximo.','Treinar adaptação do passo e liberação do pé.','Transpor soleiras e objetos no caminho.','obstáculos baixos','Intermediária','marcha','obstáculos marcha','obstáculos|marcha'],
['Mudança de direção por cones','zigue-zague','Rotação e passos multidirecionais','glúteo médio; musculatura do core','Em pé diante de cones espaçados, percurso livre.','Caminhar; reduzir velocidade antes do cone; realizar passos de curva; prosseguir.','Treinar planejamento e controle em curvas.','Circular em corredores, lojas e comunidade.','cones','Intermediária','marcha','direção cones marcha','marcha|equilíbrio'],
['Marcha lateral','deslocamento lateral','Abdução e adução','glúteo médio; adutores','Em pé ao lado de barra ou bancada.','Dar passo lateral; transferir peso; aproximar o outro pé; manter tronco orientado à frente.','Treinar locomoção lateral.','Mover-se junto a bancadas e contornar objetos.','barra opcional','Básica','marcha','marcha lateral','marcha lateral|equilíbrio'],
['Marcha para trás','retromarcha','Extensão de quadril e controle do passo','glúteo máximo; quadríceps','Em pé em percurso livre, supervisão e apoio conforme avaliação.','Olhar o ambiente antes; dar passos curtos para trás; controlar apoio; parar sob comando.','Treinar deslocamento posterior com segurança.','Recuar de móveis e ajustar posição.','barra ou dispositivo indicado','Intermediária','marcha','marcha trás','marcha|equilíbrio'],
['Marcha com metrônomo','treino de cadência','Ritmo locomotor','músculos dos membros inferiores','Em pé com metrônomo em ritmo individualizado e caminho livre.','Ouvir batidas; iniciar passos no ritmo escolhido; ajustar ou parar se perder segurança.','Explorar regularidade temporal da marcha.','Manter ritmo em percursos contínuos.','metrônomo','Intermediária','marcha','cadência ritmo marcha','marcha'],
['Parar e reiniciar a marcha','start-stop','Controle de transições da marcha','quadríceps; sóleo; musculatura do core','Em pé em percurso protegido e com comandos combinados.','Caminhar; desacelerar ao comando; estabilizar; reiniciar após novo comando.','Treinar transições entre movimento e estabilidade.','Parar em portas, filas e travessias.','marcadores opcionais','Intermediária','marcha','parar iniciar marcha','marcha|equilíbrio'],
['Circuito funcional de marcha','percurso de mobilidade','Múltiplos movimentos','músculos dos membros inferiores e tronco','Percurso com cadeira, cones e objetos, organizado conforme capacidade.','Levantar; caminhar; contornar; alcançar alvo; retornar e sentar com controle.','Integrar componentes da mobilidade em sequência.','Deslocamento doméstico e comunitário.','cadeira; cones; alvos','Avançada','função','circuito marcha funcional','marcha|levantar cadeira|obstáculos'] ],
Neuro:[
['Alcance sentado orientado à tarefa','alcance em sedestação','Tronco e membro superior','musculatura do core; deltoide; tríceps','Sedestação com pés e apoio definidos conforme avaliação.','Localizar alvo; deslocar tronco e braço; tocar ou pegar; retornar ao centro.','Treinar alcance, controle de tronco e orientação ao alvo.','Pegar objetos durante alimentação e autocuidado.','alvos ou objetos','Básica','motor','neuro alcance sentado AVE MMSS','alcançar|controle tronco'],
['Transferência sentado-em-pé segmentada','treino por fases da transferência','Quadril, joelho e tronco','quadríceps; glúteo máximo; musculatura do core','Sentado com altura, pés e assistência individualizados.','Treinar inclinação anterior; descarga nos pés; elevação; estabilização em pé; retorno.','Praticar componentes da transferência com ajuda graduada.','Independência para levantar de superfícies.','cadeira; cinto se indicado','Básica','função','neuro transferência AVE Parkinson','levantar cadeira|transferência'],
['Deslocamento de tronco sentado','transferência de peso em sedestação','Tronco e pelve','musculatura do core; oblíquos','Sentado com base protegida e mãos apoiadas se preciso.','Mover o tronco para frente, lados e diagonais; retornar ao centro; alcançar se adequado.','Treinar limites de estabilidade em sedestação.','Reposicionar-se e preparar transferências.','banco; alvos','Básica','motor','neuro tronco sedestação lesão medular','controle tronco|equilíbrio'],
['Rolamento no leito por segmentos','rolar no leito','Tronco, cintura escapular e pelve','oblíquos; glúteos; músculos dos membros','Decúbito com espaço e assistência planejados.','Direcionar olhar e braço; mover cintura escapular; conduzir pelve e pernas; estabilizar de lado.','Praticar mobilidade no leito e dissociação de cinturas.','Mudar de posição e preparar-se para sentar.','leito; lençol deslizante se indicado','Básica','motor','neuro leito AVE lesão medular','transferência leito|controle tronco'],
['Ponte assistida para mobilidade no leito','elevação de quadril funcional','Extensão de quadril','glúteo máximo; isquiotibiais','Decúbito dorsal com pés posicionados e ajuda definida.','Preparar pés; elevar a pelve com comando/assistência; deslocar ou sustentar; retornar.','Facilitar reposicionamento e participação ativa.','Vestir-se e ajustar posição no leito.','leito','Básica','função','neuro ponte leito lesão medular','transferência leito'],
['Toques alternados em alvos','coordenação alvo-alvo','Membro superior','deltoide; tríceps; musculatura da mão','Sentado ou em pé com alvos visíveis e suporte adequado.','Tocar alvos em sequência; variar lado e direção; retornar à posição inicial.','Treinar precisão, alternância e coordenação.','Alcançar comandos, utensílios e objetos.','alvos coloridos','Básica','motor','neuro coordenação MMSS AVE','coordenação|alcançar'],
['Deslizamento bilateral de mãos na mesa','alcance bilateral apoiado','Ombro, cotovelo e tronco','serrátil anterior; tríceps; musculatura do core','Sentado diante de mesa, mãos sobre pano ou prancha.','Deslizar as duas mãos à frente; acompanhar com tronco; retornar usando assistência necessária.','Promover participação bilateral e alcance apoiado.','Empurrar objetos e alcançar sobre a mesa.','mesa; pano ou prancha','Básica','motor','neuro bilateral MMSS AVE','alcançar|controle tronco'],
['Passos multidirecionais com comando','stepping por direção','Membros inferiores e tronco','glúteo médio; quadríceps; tibial anterior','Em pé com proteção, apoio e assistência definidos.','Responder a comando de direção; transferir peso; dar passo; retornar à base.','Treinar seleção motora, equilíbrio e passos protetores.','Mudar direção e ajustar-se no ambiente.','marcadores; cinto se indicado','Intermediária','motor','neuro passo coordenação Parkinson','equilíbrio|marcha'],
['Ortostatismo assistido com alinhamento','ficar em pé com suporte','Extensão de membros e controle postural','quadríceps; glúteo máximo; sóleo','Em pé com assistência e suportes prescritos.','Organizar pés/pelve/tronco; distribuir peso; manter pelo tempo tolerado; retornar com ajuda.','Treinar tolerância e participação no ortostatismo.','Transferências e preparação para marcha.','barra; órtese/dispositivo se prescritos','Básica','equilíbrio','neuro ortostatismo lesão medular AVE','transferência|equilíbrio'],
['Treino de passo com pista visual','passo sobre linha','Avanço do membro','iliopsoas; tibial anterior; quadríceps','Em pé diante de linha contrastante, assistência definida.','Preparar peso; avançar o pé além da linha; apoiar; repetir com pistas reduzidas se possível.','Usar pista externa para organizar amplitude do passo.','Iniciação e continuidade da marcha.','fita contrastante','Básica','marcha','neuro pista visual Parkinson marcha','marcha'],
['Dupla tarefa motora simples','marcha com objeto leve','Marcha e tarefa simultânea','músculos de marcha e membro superior','Em percurso seguro, tarefa primária já estável e supervisão adequada.','Caminhar enquanto segura objeto leve ou responde a comando simples; parar se a qualidade cair.','Observar e treinar divisão de atenção de forma graduada.','Locomoção enquanto conversa ou transporta item.','objeto leve','Avançada','marcha','neuro dupla tarefa Parkinson','marcha|dupla tarefa'],
['Transferência cadeira-leito simulada','transferência lateral ou em pé','Múltiplas articulações','quadríceps; glúteos; membros superiores','Superfícies travadas, altura e assistência definidas antes de iniciar.','Planejar direção; posicionar pés/mãos; elevar ou deslizar; girar; controlar a chegada.','Treinar sequência segura e participação na transferência.','Mover-se entre cama, cadeira e vaso sanitário.','cadeira; leito; tábua se prescrita','Intermediária','função','neuro transferência lesão medular AVE','transferência'],
['Alcance com membro inferior em alvo','toque de cones com o pé','Quadril, joelho e tornozelo','iliopsoas; quadríceps; tibial anterior','Sentado ou em pé conforme controle e assistência.','Elevar o pé; tocar alvo; retornar; alternar direção ou lado sem perder postura.','Treinar seletividade, coordenação e controle do membro inferior.','Posicionar os pés e desviar de obstáculos.','cones ou marcas','Básica','motor','neuro MMII coordenação','coordenação|obstáculos'] ],
Pediatria:[
['Alcance por brinquedo sentado','brincadeira de alcançar','Tronco e membros superiores','musculatura postural; deltoide','Sentado em apoio apropriado, brinquedo dentro de alcance possível.','Apresentar o brinquedo; permitir iniciativa; facilitar deslocamento; devolver ao centro.','Estimular controle de tronco, alcance e exploração.','Brincar sentado e interagir com objetos.','brinquedo adequado à idade','Básica','motor','pediatria alcance tronco','alcançar|controle tronco'],
['Sentar em bola com deslocamentos','equilíbrio na bola','Tronco e pelve','musculatura do core; estabilizadores pélvicos','Sentado na bola com pés apoiados e adulto protegendo pelve/tronco.','Realizar deslocamentos pequenos e previsíveis; esperar ajuste; retornar ao centro.','Explorar respostas posturais em brincadeira.','Controle sentado durante atividades.','bola terapêutica','Intermediária','equilíbrio','pediatria bola equilíbrio','equilíbrio|controle tronco'],
['Circuito de almofadas','ilha de almofadas','Múltiplas articulações','músculos dos membros inferiores e tronco','Diante de almofadas firmes, percurso curto e proteção próxima.','Subir, atravessar e descer; usar história ou alvo; adaptar distância e ajuda.','Estimular equilíbrio dinâmico e planejamento motor.','Explorar diferentes superfícies no brincar.','almofadas firmes','Intermediária','função','pediatria circuito motricidade grossa','equilíbrio|obstáculos'],
['Engatinhar por túnel','circuito em quatro apoios','Ombros, quadris e tronco','serrátil anterior; glúteos; musculatura do core','Quatro apoios diante de túnel curto e ventilado.','Atrair com brinquedo; avançar alternando mãos e joelhos; permitir pausas e saída livre.','Estimular coordenação bilateral e suporte de peso.','Exploração no chão e transições.','túnel lúdico','Básica','motor','pediatria engatinhar coordenação','coordenação|motricidade grossa'],
['Transição ajoelhado para em pé','meio-ajoelhado para levantar','Quadril, joelho e tronco','glúteo máximo; quadríceps; musculatura do core','Ajoelhado diante de apoio ou brinquedo elevado.','Levar um pé à frente; transferir peso; levantar com ajuda necessária; retornar.','Praticar transição postural e força funcional.','Levantar do chão durante brincadeiras.','apoio; colchonete','Intermediária','função','pediatria transição ajoelhado','levantar chão|transferência'],
['Chutar bola parada','chute ao alvo','Quadril, joelho e tornozelo','quadríceps; iliopsoas; glúteo médio','Em pé diante de bola grande, com apoio se necessário.','Transferir peso; levar a perna livre atrás; chutar em direção ao alvo; recuperar base.','Estimular apoio unilateral, coordenação e força.','Brincar com bola e iniciar habilidades locomotoras.','bola; alvo','Básica','motor','pediatria chute coordenação','coordenação|equilíbrio'],
['Caminhar sobre linha colorida','trilha no chão','Marcha e equilíbrio','músculos dos membros inferiores e tronco','No início de linha larga e contrastante.','Seguir a linha; parar em símbolos; mudar direção conforme comando lúdico.','Treinar direção, controle de passos e atenção.','Locomoção em percursos e jogos.','fita colorida','Básica','marcha','pediatria linha marcha','marcha|equilíbrio'],
['Arremesso de bola em cesto','jogar e acertar','Ombro, cotovelo e tronco','deltoide; tríceps; musculatura do core','Sentado ou em pé, cesto a distância alcançável.','Segurar a bola; mirar; arremessar; buscar outra bola com segurança.','Estimular coordenação olho-mão e alcance.','Brincadeiras com bola e participação escolar.','bolas leves; cesto','Básica','motor','pediatria arremesso coordenação','coordenação|alcançar'],
['Imitação de animais','andar como animais','Múltiplas articulações','musculatura global','Espaço livre, tarefa demonstrada e adaptada à criança.','Escolher um animal; imitar postura/deslocamento por trecho curto; alternar e descansar.','Explorar força, coordenação e criatividade motora.','Brincadeira ativa e motricidade grossa.','cartas ou figuras opcionais','Intermediária','função','pediatria animais motricidade grossa','coordenação|motricidade grossa'],
['Subir e descer degrau lúdico','degrau do tesouro','Quadril, joelho e tornozelo','quadríceps; glúteo máximo; panturrilha','Diante de degrau baixo com apoio e objeto motivador.','Subir para alcançar o objeto; estabilizar; descer com ajuda; alternar quando apropriado.','Treinar força funcional, equilíbrio e planejamento.','Escadas e desníveis no ambiente.','degrau; brinquedo; apoio','Intermediária','função','pediatria degrau escada','subir escada|equilíbrio'] ]};



presets['Cardiorrespiratória']={region:'Sistema cardiorrespiratório e corpo inteiro',joint:'Múltiplas articulações e padrão ventilatório',aux:'diafragma, músculos respiratórios, membros superiores, membros inferiores e controle postural',capacity:'controle ventilatório, tolerância ao esforço, mobilidade torácica e participação funcional',progression:'Progredir duração, complexidade ou demanda somente com monitoramento, estabilidade clínica e resposta adequada.',regression:'Reduzir duração, amplitude e demanda; usar posição apoiada, pausas e maior supervisão.',compensation:'Prender a respiração, acelerar sem controle, elevar excessivamente os ombros ou perder estabilidade.'};
presets['Condicionamento']={region:'Corpo inteiro e capacidade funcional',joint:'Múltiplas articulações',aux:'músculos dos membros inferiores e superiores, musculatura respiratória e estabilizadores do tronco',capacity:'tolerância ao esforço, resistência funcional, ritmo e recuperação',progression:'Aumentar uma variável por vez, como duração, percurso ou resistência, usando resposta e objetivo para orientar.',regression:'Diminuir bloco de atividade, ampliar pausa, usar apoio ou escolher tarefa sentada.',compensation:'Ritmo incompatível com a capacidade, prender a respiração, depender de impulso ou manter a tarefa apesar de sinais preocupantes.'};
presets['Funcional e cotidiano']={region:'Corpo inteiro e atividades de vida diária',joint:'Múltiplas articulações',aux:'cadeias musculares e estratégias posturais envolvidas na tarefa',capacity:'força funcional, coordenação, mobilidade, autonomia e participação',progression:'Aproximar gradualmente altura, carga, distância e contexto da tarefa real mantendo segurança.',regression:'Simplificar etapas, reduzir carga ou alcance, elevar superfícies e oferecer apoio ou assistência.',compensation:'Organização insegura do ambiente, pressa, base inadequada, alcance além do controle ou carga distante do corpo.'};
presets['Mobilidade no leito']={region:'Leito, sedestação e transferências',joint:'Tronco e múltiplas articulações',aux:'musculatura do tronco, cinturas escapular e pélvica e membros',capacity:'mobilidade no leito, controle postural, transferências e prevenção de imobilidade',progression:'Reduzir gradualmente assistência e pistas ou integrar mais etapas somente com estabilidade e segurança.',regression:'Segmentar a tarefa, ajustar a altura do leito e usar apoio, lençol ou assistência treinada.',compensation:'Tração inadequada dos membros, prender a respiração, executar sem preparar dispositivos ou perder estabilidade.'};

rows['Cardiorrespiratória']=[
['Percepção respiratória em posição apoiada','observação ventilatória','Padrão ventilatório','diafragma; músculos respiratórios','Sentado ou semissentado com tronco e membros apoiados.','Observar ritmo e regiões de movimento sem tentar aumentar o volume; relaxar mandíbula e ombros; registrar conforto.','Aumentar percepção do padrão ventilatório e preparar estratégias respiratórias.','Reconhecer e organizar a respiração durante repouso e recuperação.','cadeira ou encosto','Básica','motor','respiração percepção ventilação','dispneia|recuperação'],
['Respiração diafragmática orientada','respiração abdominal','Controle inspiratório','diafragma','Semissentado ou sentado, uma mão sobre abdome e outra no tórax, sem compressão.','Inspirar de forma confortável percebendo expansão; expirar sem forçar; evitar volumes excessivos ou tontura.','Explorar coordenação e conforto ventilatório.','Autorregulação em repouso e entre tarefas.','apoio confortável','Básica','motor','diafragma respiração controle ventilatório','dispneia|recuperação'],
['Expansão costal lateral com contato','respiração costal lateral','Mobilidade torácica respiratória','diafragma; intercostais','Sentado, mãos ou faixa leve sobre as regiões laterais das costelas.','Inspirar percebendo expansão lateral contra contato leve; expirar relaxando; não comprimir nem forçar.','Explorar expansão torácica e consciência respiratória.','Preparação para tarefas que exigem coordenação respiratória.','mãos ou faixa sem resistência','Básica','mobilidade','expansão costal torácica respiração','mobilidade torácica|dispneia'],
['Expansão torácica com elevação dos braços','respiração com alcance','Inspiração e flexão de ombro','diafragma; intercostais; deltoide','Sentado, braços apoiados ao lado do corpo e amplitude de ombro avaliada.','Elevar os braços durante inspiração confortável; baixar durante expiração; ajustar amplitude e ritmo.','Integrar mobilidade de tórax, ombros e padrão ventilatório.','Alcançar e movimentar membros superiores sem perder coordenação respiratória.','nenhum','Básica','motor','respiração braços expansão torácica','alcançar|dispneia'],
['Expiração com lábios semicerrados','expiração lenta com lábios franzidos','Controle expiratório','músculos expiratórios','Sentado apoiado e relaxado.','Inspirar confortavelmente; expirar de modo suave por lábios semicerrados, sem prolongar até desconforto.','Explorar uma estratégia de controle expiratório.','Recuperação entre esforços quando ensinada e considerada útil na avaliação.','nenhum','Básica','motor','lábios semicerrados expiração dispneia','dispneia|recuperação'],
['Posição inclinada apoiada para recuperação','posição de alívio apoiada','Controle postural e ventilatório','músculos respiratórios; estabilizadores do tronco','Sentado, antebraços apoiados em mesa ou coxas, pés estáveis.','Ajustar inclinação confortável; relaxar ombros; usar o padrão respiratório já orientado; retornar devagar.','Experimentar posição apoiada durante recuperação.','Gerenciar pausas em tarefas conforme plano individual.','mesa ou apoio','Básica','função','posição inclinada recuperação respiração','dispneia|recuperação'],
['Respiração ritmada no sentar e levantar','expirar no esforço','Transferência com coordenação respiratória','quadríceps; glúteo máximo; músculos respiratórios','Sentado em cadeira estável, pés organizados e assistência definida.','Preparar inspiração confortável; levantar durante expiração sem prender o ar; estabilizar; sentar controlando o ritmo.','Integrar respiração e transferência funcional.','Levantar da cadeira com melhor organização do esforço.','cadeira','Básica','função','respiração sentar levantar esforço','levantar cadeira|dispneia'],
['Respiração ritmada no degrau','expiração no step','Subida de degrau e padrão ventilatório','quadríceps; glúteo máximo; panturrilha; músculos respiratórios','Diante de degrau baixo com apoio, estabilidade clínica e assistência planejada.','Preparar; subir coordenando a expiração; estabilizar; descer; pausar conforme resposta.','Integrar controle respiratório e tarefa de degrau.','Subir pequenos desníveis e escadas.','degrau; apoio','Intermediária','função','respiração degrau escada dispneia','subir escada|dispneia'],
['Mobilidade torácica com respiração','abertura de braços respiratória','Extensão e rotação torácica','extensores torácicos; intercostais','Sentado, braços cruzados ou abertos conforme controle.','Inspirar enquanto abre suavemente o tórax; expirar ao retornar; alternar direção sem forçar.','Associar mobilidade torácica ao ritmo ventilatório.','Mudar postura e alcançar em tarefas sentadas.','cadeira','Básica','mobilidade','mobilidade torácica respiração','mobilidade torácica'],
['Expiração forçada aberta orientada','huff orientado','Fluxo expiratório','músculos expiratórios','Sentado apoiado após avaliação da necessidade e demonstração profissional.','Inspirar em volume confortável; expirar com boca aberta como se embaçasse um vidro; recuperar sem repetir excessivamente.','Explorar técnica de fluxo expiratório quando retenção de secreção foi avaliada.','Auxiliar manejo de secreção apenas quando indicado e ensinado.','recipiente para secreção se necessário','Intermediária','motor','huff secreção higiene brônquica','secreção'],
['Treino muscular inspiratório com dispositivo','IMT supervisionado','Inspiração resistida','diafragma; músculos inspiratórios','Sentado, dispositivo individual limpo e carga definida por avaliação específica.','Selar o bocal; inspirar contra resistência prescrita; expirar livremente; interromper conforme critérios definidos.','Treinar musculatura inspiratória quando formalmente indicada.','Apoiar capacidade ventilatória em programa individualizado.','dispositivo inspiratório individual','Intermediária','força','treino muscular inspiratório dispositivo','dispneia|condicionamento'],
['Elevação alternada de braços com ritmo respiratório','alcance alternado respiratório','Flexão de ombro alternada','deltoide; serrátil anterior; músculos respiratórios','Sentado, pés apoiados e braços ao lado.','Elevar um braço durante inspiração confortável; baixar ao expirar; alternar e pausar se perder ritmo.','Combinar resistência leve de membros superiores e controle ventilatório.','Pentear cabelo, vestir-se e alcançar objetos.','peso leve opcional','Básica','função','MMSS respiração alcance condicionamento','alcançar|dispneia']
];

rows['Condicionamento']=[
['Marcha estacionária sentada','marchar sentado','Flexão alternada de quadril','iliopsoas; quadríceps','Sentado com pés apoiados e tronco estável.','Elevar um pé por vez em ritmo confortável; manter respiração; usar blocos curtos e pausas.','Treinar ritmo e resistência em posição apoiada.','Preparar membros inferiores para marcha e transferências.','cadeira','Básica','marcha','marcha sentada condicionamento','marcha|fadiga'],
['Marcha estacionária em pé com apoio','marchar no lugar','Flexão alternada de quadril e apoio','iliopsoas; glúteo médio; panturrilha','Em pé junto a apoio estável, assistência e monitoramento definidos.','Alternar elevação dos pés sem acelerar; manter postura e respiração; pausar com base ampla.','Desenvolver resistência e transferência de peso.','Preparar caminhada em espaço reduzido.','apoio estável','Básica','marcha','marcha estacionária condicionamento','marcha|equilíbrio|fadiga'],
['Pedalada estacionária leve','bicicleta ergométrica','Movimento cíclico de membros inferiores','quadríceps; glúteos; panturrilha','Sentado na bicicleta ajustada, pés fixos e resistência inicial definida.','Pedalar em ritmo confortável; monitorar sintomas e esforço; recuperar gradualmente ao finalizar.','Treinar tolerância ao esforço em tarefa cíclica sem impacto.','Melhorar capacidade para deslocamentos prolongados.','bicicleta ergométrica','Básica','marcha','bicicleta condicionamento aeróbico','fadiga|condicionamento'],
['Cicloergômetro de braços leve','ergômetro de membros superiores','Movimento cíclico de braços','deltoide; bíceps; tríceps','Sentado diante do ergômetro ajustado, tronco apoiado se necessário.','Girar em ritmo e resistência individualizados; manter respiração; reduzir antes de parar.','Treinar tolerância usando membros superiores.','Sustentar tarefas repetidas de braços.','cicloergômetro de braços','Intermediária','função','ergômetro braços condicionamento','fadiga|MMSS'],
['Circuito sentado de três tarefas','circuito na cadeira','Múltiplos movimentos sentados','quadríceps; deltoide; musculatura do core','Sentado em cadeira firme com três tarefas simples preparadas.','Alternar marcha sentada, alcance e extensão de joelho; realizar pausa entre blocos; registrar resposta.','Integrar resistência de membros e tronco com baixo risco postural.','Tolerar sequência de autocuidado sentado.','cadeira; bola leve','Básica','função','circuito sentado condicionamento','fadiga|função manual'],
['Circuito funcional em pé de três estações','estações funcionais','Marcha, alcance e transferência','membros inferiores; membros superiores; core','Em área protegida com cadeira, alvo e percurso curto.','Alternar sentar-levantar, caminhada curta e alcance; respeitar pausas; completar apenas estações seguras.','Treinar tolerância em sequência funcional.','Combinar tarefas domésticas e deslocamento.','cadeira; alvo; marcadores','Intermediária','função','circuito funcional condicionamento','marcha|levantar cadeira|fadiga'],
['Passos em degrau por tempo','step de resistência','Subida e descida de degrau','quadríceps; glúteo máximo; panturrilha','Diante de degrau baixo e apoio, capacidade e monitoramento definidos.','Subir e descer em ritmo controlado por bloco curto; alternar perna quando apropriado; recuperar.','Treinar resistência específica para degraus.','Subir escadas e desníveis.','degrau; apoio; cronômetro','Intermediária','função','degrau condicionamento escada','subir escada|fadiga'],
['Caminhada com pausas planejadas','intervalos de caminhada','Marcha contínua ou intervalada','músculos dos membros inferiores','Em percurso conhecido, apoio e duração inicial definidos.','Caminhar no ritmo-alvo; pausar antes de perda relevante de qualidade; retomar se a resposta permitir.','Desenvolver tolerância à caminhada com dose observável.','Aumentar participação em deslocamentos cotidianos.','cronômetro; dispositivo se indicado','Básica','marcha','caminhada intervalada condicionamento','marcha|fadiga'],
['Dança com passos simples','sequência rítmica','Passos multidirecionais','membros inferiores; musculatura do core','Em pé ou sentado, música e movimentos compatíveis com segurança e preferência.','Repetir sequência curta de passos ou movimentos; acompanhar ritmo confortável; pausar livremente.','Trabalhar resistência, ritmo e participação de forma significativa.','Participar de atividade rítmica e recreativa escolhida pela pessoa.','música opcional; apoio','Intermediária','função','dança ritmo condicionamento','coordenação|fadiga'],
['Transporte leve em percurso curto','caminhada com objeto leve','Marcha com tarefa de membros superiores','membros inferiores; flexores dos dedos; core','Em pé com objeto leve seguro e trajeto desobstruído.','Carregar junto ao corpo; caminhar; apoiar o objeto; recuperar; ajustar carga e distância separadamente.','Integrar tolerância à marcha e transporte.','Levar roupas, utensílios ou compras leves.','objeto leve; superfície de apoio','Intermediária','função','carregar condicionamento tarefa dupla','marcha|preensão|fadiga']
];

rows['Funcional e cotidiano']=[
['Transferência do chão por etapas','levantar do chão','Transições ajoelhado, apoio e ortostatismo','quadríceps; glúteos; membros superiores; core','No chão sobre colchonete, apoio firme próximo e assistência planejada.','Passar para quatro apoios ou ajoelhado; levar um pé à frente; usar apoio; levantar; praticar retorno separadamente.','Treinar estratégia individual para levantar do chão.','Recuperar-se após atividade no solo ou queda sem lesão, quando avaliado como seguro.','colchonete; apoio firme','Avançada','função','levantar chão transferência cotidiano','levantar chão|transferência'],
['Entrada e saída de carro simulada','transferência veicular','Sentar, girar e mover pernas','quadríceps; flexores de quadril; core','Diante de banco estável que simule a altura do veículo, ambiente protegido.','Sentar de costas para o banco; estabilizar; girar tronco e pernas em etapas; inverter a sequência para sair.','Praticar componentes de transferência veicular.','Entrar e sair de automóvel.','banco; marcação de porta simulada','Intermediária','função','carro transferência cotidiano','transferência'],
['Vestir o pé sentado','simulação de calçar meia','Flexão de quadril, alcance e função manual','iliopsoas; core; musculatura da mão','Sentado estável, pé acessível por estratégia avaliada e objeto de treino limpo.','Aproximar o pé ou usar apoio; alcançar sem perder equilíbrio; simular vestir; retornar.','Integrar mobilidade, equilíbrio sentado e destreza.','Calçar meias e sapatos.','faixa ou meia de treino','Básica','função','vestir calçar alcance cotidiano','autocuidado|alcançar'],
['Alcance em armário baixo e alto','organizar prateleiras','Agachar e elevar braços','quadríceps; glúteos; deltoide; core','Em pé entre duas superfícies estáveis com objetos leves.','Mover objetos entre alturas; aproximar-se de cada alvo; reorganizar a base antes de alcançar.','Treinar alcance em diferentes alturas e planejamento da tarefa.','Guardar utensílios, roupas e mantimentos leves.','prateleiras; objetos leves','Intermediária','função','armário alcance cotidiano','abaixar|alcançar alto'],
['Empurrar e puxar objeto com rodas','carrinho funcional','Passo, empurrar e puxar','tríceps; dorsais; membros inferiores; core','Em pé diante de carrinho leve estável em percurso livre.','Organizar mãos e base; empurrar trecho curto; parar; reposicionar; puxar somente se previsto e seguro.','Treinar produção de força e passos com objeto móvel.','Mover carrinho, porta leve ou cadeira vazia.','carrinho estável','Intermediária','função','empurrar puxar cotidiano','empurrar|marcha'],
['Dobrar e transportar roupas','tarefa de lavanderia','Alcance, preensão e transporte','deltoide; flexores dos dedos; core','Em pé ou sentado diante de mesa, cesto leve e peças de treino.','Pegar peça; dobrar; colocar no cesto; transportar curta distância; apoiar antes de repetir.','Integrar destreza, alcance e tolerância à tarefa.','Organizar roupas e lavanderia.','roupas; mesa; cesto leve','Básica','função','lavanderia roupas cotidiano','preensão|marcha|alcançar'],
['Preparo de refeição simulado','organização em bancada','Permanência em pé, alcance e função manual','membros inferiores; musculatura da mão; core','Diante de bancada organizada com objetos sem corte e leves.','Alternar alcance, transporte curto e manipulação; mudar apoio; usar banco ou pausa conforme plano.','Treinar tolerância e organização em tarefa doméstica.','Preparar alimentos simples com segurança.','bancada; utensílios seguros','Intermediária','função','cozinha bancada cotidiano','preensão|alcançar|fadiga'],
['Sentar e levantar de altura baixa simulada','transferência de vaso sanitário','Flexão de quadril/joelho e extensão','quadríceps; glúteo máximo; core','Diante de cadeira firme em altura individualizada, barras ou apoio se necessários.','Recuar até sentir a superfície; controlar a descida; reorganizar pés e tronco; levantar usando apoio previsto.','Treinar transferência em superfície mais baixa.','Uso do vaso sanitário e assentos baixos.','cadeira ajustável; apoio','Intermediária','função','assento baixo banheiro transferência','levantar cadeira|autocuidado'],
['Abrir porta e atravessar','manejo de porta','Preensão, passo e controle postural','flexores dos dedos; deltoide; membros inferiores','Diante de porta leve ou simulador, espaço livre e apoio se indicado.','Segurar maçaneta; abrir mantendo base; dar passos para atravessar; controlar o fechamento sem pressa.','Integrar função manual, equilíbrio e deslocamento.','Circular entre cômodos e ambientes públicos.','porta leve ou simulador','Intermediária','função','porta preensão cotidiano','preensão|marcha|equilíbrio'],
['Organização de objetos em sequência','guardar compras leves','Agachar, transportar e alcançar','quadríceps; glúteos; deltoide; core','Objetos leves distribuídos entre mesa, cesta e prateleira acessível.','Escolher sequência; mover um objeto por vez; aproximar-se do alvo; usar pausa; revisar segurança.','Treinar planejamento, alcance e resistência em tarefa encadeada.','Guardar compras e organizar ambiente.','objetos leves; cesta; prateleira','Intermediária','função','organização compras cotidiano','abaixar|alcançar|fadiga'],
['Virar na cama e alcançar objeto','mobilidade noturna simulada','Rolamento e alcance','oblíquos; deltoide; glúteos','Decúbito no leito com objeto seguro ao lado e espaço protegido.','Girar cabeça e braço; rolar por segmentos; alcançar o objeto; retornar ou estabilizar de lado.','Integrar mobilidade no leito e alcance.','Ajustar roupa de cama e alcançar item próximo.','leito; objeto leve','Básica','função','cama alcance cotidiano','transferência leito|alcançar'],
['Dupla tarefa doméstica simples','caminhar e nomear itens','Marcha e tarefa cognitiva simples','membros inferiores; core','Em percurso protegido, marcha já estável e supervisão compatível.','Caminhar enquanto nomeia categorias ou leva objeto leve; parar se segurança ou qualidade reduzir.','Observar e treinar divisão de atenção em contexto funcional.','Conversar ou organizar itens durante deslocamento.','objetos leves opcionais','Avançada','função','dupla tarefa doméstica cotidiano','marcha|dupla tarefa']
];

rows['Mobilidade no leito']=[
['Bombeamento de tornozelos no leito','ankle pumps','Dorsiflexão e flexão plantar','tibial anterior; gastrocnêmio; sóleo','Decúbito ou semissentado, pernas apoiadas e tornozelos livres.','Alternar ponta do pé e dorsiflexão em amplitude confortável; evitar prender a respiração; pausar se houver câimbra.','Manter movimento ativo distal durante períodos de menor mobilidade.','Preparar pernas para sentar, levantar e caminhar.','leito','Básica','mobilidade','tornozelo leito mobilidade hospitalar','mobilidade tornozelo'],
['Deslizamento unilateral do braço no leito','alcance apoiado no leito','Flexão de ombro apoiada','deltoide; serrátil anterior','Decúbito ou semissentado, braço apoiado sobre lençol e amplitude permitida.','Deslizar a mão em direção à cabeceira ou lateral; acompanhar com olhar; retornar sem elevar o ombro.','Manter alcance ativo com suporte da superfície.','Reposicionar objetos e participar do autocuidado no leito.','leito; pano deslizante','Básica','mobilidade','ombro leito hospitalar alcance','alcançar|mobilidade ombro'],
['Flexão alternada de quadril no leito','marcha em decúbito','Flexão de quadril e joelho','iliopsoas; quadríceps','Decúbito dorsal, pés apoiados ou pernas estendidas conforme capacidade.','Deslizar ou elevar um pé de cada vez; manter pelve confortável; alternar com pausa.','Treinar ativação alternada dos membros inferiores.','Preparar rolamento, ponte e saída do leito.','leito','Básica','motor','marcha leito hospitalar quadril','transferência leito'],
['Rolamento com alcance ao trilho','rolar usando alvo','Rotação de tronco e quadril','oblíquos; glúteos; deltoide','Decúbito, trilho ou alvo seguro ao alcance e dispositivos organizados.','Direcionar olhar e braço; flexionar a perna se apropriado; rolar; estabilizar; retornar com assistência planejada.','Treinar participação ativa no reposicionamento.','Virar no leito e preparar cuidados.','leito; trilho se disponível','Básica','função','rolamento leito hospitalar','transferência leito'],
['Passagem de deitado para sentado por etapas','saída do leito','Rolamento, apoio de braço e descida das pernas','oblíquos; tríceps; flexores de quadril','Decúbito próximo à borda segura, leito travado e assistência definida.','Rolar de lado; levar pernas para fora; empurrar o leito com braços; alcançar sedestação; estabilizar antes de prosseguir.','Praticar sequência de saída do leito.','Sentar para autocuidado, alimentação e transferência.','leito regulável','Intermediária','função','deitado sentado leito hospitalar','transferência leito'],
['Controle de sedestação à beira do leito','sentar na borda','Controle de tronco e apoio dos pés','core; extensores do tronco','Sentado à beira do leito com pés apoiados, proteção e monitoramento necessários.','Encontrar posição estável; manter olhar; realizar pequenos ajustes; retornar ao leito se a resposta não for adequada.','Treinar tolerância e controle sentado.','Preparar transferências e atividades fora do leito.','leito; apoio para pés','Básica','equilíbrio','sedestação beira leito hospitalar','controle tronco|transferência'],
['Alcance curto em sedestação no leito','alcançar na borda','Alcance e controle sentado','deltoide; core','Sentado protegido, alvo dentro da base ou pouco além, pés apoiados.','Alcançar em uma direção; retornar ao centro; alternar apenas se mantiver estabilidade.','Integrar controle de tronco e membro superior.','Alimentação, higiene e preparação para transferência.','alvo leve; leito','Básica','motor','alcance sedestação leito hospitalar','alcançar|controle tronco'],
['Transferência lateral por pequenos deslocamentos','scooting sentado','Descarga e avanço da pelve','tríceps; quadríceps; core','Sentado em superfície firme, pés e mãos posicionados, assistência definida.','Inclinar o tronco; aliviar um lado da pelve; deslocar pequena distância; reorganizar base; alternar.','Treinar reposicionamento sentado.','Aproximar-se da borda e preparar transferência.','leito ou banco','Intermediária','função','scooting deslocamento sentado hospitalar','transferência'],
['Ortostatismo à beira do leito','ficar em pé junto ao leito','Transferência sentado-em-pé','quadríceps; glúteo máximo; panturrilha','Sentado, leito travado, calçado, dispositivo e assistência preparados.','Organizar pés; inclinar tronco; levantar; estabilizar com apoio; sentar se resposta ou segurança não forem adequadas.','Treinar transferência e tolerância em pé.','Preparar higiene, troca de superfície e marcha.','leito; dispositivo indicado','Intermediária','função','ortostatismo leito hospitalar','levantar cadeira|transferência'],
['Passos curtos ao lado do leito','marcha beira leito','Marcha com apoio próximo','membros inferiores; core','Em pé estável, percurso livre, linhas e dispositivos organizados, assistência definida.','Transferir peso; dar poucos passos; virar ou retornar conforme plano; sentar com controle.','Praticar locomoção inicial em ambiente protegido.','Progredir mobilidade dentro do quarto.','dispositivo se indicado; leito','Intermediária','marcha','marcha beira leito hospitalar','marcha|transferência']
];

rows.Coluna.push(
['Rock-back em quatro apoios','sentar para trás em quatro apoios','Flexão de quadril com controle do tronco','glúteos; musculatura do core','Quatro apoios, mãos sob ombros e joelhos em apoio confortável.','Levar o quadril lentamente em direção aos calcanhares dentro da amplitude tolerada; manter respiração; retornar.','Explorar movimento de quadril e tronco em base estável.','Abaixar-se, alcançar superfícies baixas e variar posições.','colchonete','Básica','mobilidade','rock back quadril lombalgia mobilidade','mobilidade tronco|abaixar'],
['Rotação lumbopélvica em decúbito','joelhos para os lados','Rotação confortável de tronco e pelve','oblíquos; musculatura do core','Decúbito dorsal, joelhos flexionados e pés apoiados.','Mover os joelhos juntos para um lado em amplitude confortável; retornar ao centro; alternar sem forçar.','Explorar mobilidade lumbopélvica e confiança no movimento.','Virar no leito e mudar a orientação do tronco.','colchonete','Básica','mobilidade','rotação lombopélvica lombalgia leito','mobilidade tronco|transferência leito'],
['Dobradiça de quadril com bastão','hip hinge','Flexão de quadril com controle do tronco','glúteo máximo; isquiotibiais; musculatura do core','Em pé, bastão em contato com cabeça, região torácica e sacro, base confortável.','Levar o quadril para trás com joelhos levemente flexionados; manter os contatos possíveis; retornar usando quadris.','Treinar estratégia de quadril em tarefas de inclinação.','Aproximar-se de bancadas e preparar levantamento de objetos.','bastão','Intermediária','motor','hip hinge dobradiça lombalgia levantar objeto','abaixar|controle tronco'],
['Levantar objeto de superfície elevada','levantamento funcional de caixa','Quadril, joelho e tronco','glúteo máximo; quadríceps; musculatura do core','Em pé diante de objeto leve sobre superfície elevada, espaço livre.','Aproximar o objeto; organizar a base; segurar; levantar sem pressa; aproximar do corpo; recolocar com controle.','Praticar uma estratégia individualizada para levantar e colocar objetos.','Tarefas domésticas e ocupacionais com cargas leves.','caixa leve; mesa','Intermediária','função','levantar objeto lombalgia tarefa funcional','abaixar|levantar cadeira'],
['Transporte bilateral de objeto leve','carregar caixa junto ao corpo','Marcha com carga externa','membros inferiores; flexores dos dedos; musculatura do core','Em pé, objeto leve seguro entre as mãos e percurso livre.','Segurar o objeto próximo ao corpo; caminhar trecho curto; parar; apoiar o objeto com controle.','Integrar marcha, preensão e tolerância ao transporte.','Levar compras leves e objetos domésticos.','caixa ou objeto leve','Intermediária','função','carregar objeto lombalgia marcha funcional','marcha|preensão'],
['Prancha lateral com joelhos apoiados','prancha lateral curta','Estabilização lateral do tronco','oblíquos; glúteo médio','Decúbito lateral, joelhos flexionados e antebraço apoiado sob o ombro.','Organizar ombro; elevar a pelve em alavanca curta; respirar; retornar lentamente.','Treinar capacidade lateral de tronco e quadril.','Estabilidade em transferências, alcance e tarefas assimétricas.','colchonete','Intermediária','força','prancha lateral core lombalgia','controle tronco'],
['Pressão antirotação com faixa','Pallof press adaptado','Controle de rotação do tronco','oblíquos; musculatura do core','Em pé ou sentado de lado para faixa fixada com segurança, mãos junto ao peito.','Afastar as mãos do tronco sem deixar a faixa girar o corpo; retornar; trocar o lado da montagem.','Treinar controle do tronco diante de força rotacional graduada.','Empurrar, carregar e manter orientação do tronco.','faixa elástica; ponto de fixação seguro','Intermediária','força','antirrotação faixa core lombalgia','controle tronco|empurrar'],
['Isometria cervical multidirecional suave','resistência manual cervical','Controle isométrico cervical','flexores; extensores; flexores laterais cervicais','Sentado com cabeça alinhada, mão apoiada suavemente na testa, lateral ou parte posterior.','Pressionar levemente a cabeça contra a mão sem produzir movimento visível; respirar; relaxar e mudar a direção.','Explorar ativação cervical em posição neutra.','Sustentar orientação da cabeça em tarefas sentadas.','mão ou toalha','Básica','força','isometria cervical cervicalgia pescoço','postura'],
['Caminhada intervalada autorregulada','caminhada com pausas planejadas','Marcha e condicionamento','músculos dos membros inferiores e tronco','Em percurso seguro, distância e apoio definidos após avaliação.','Caminhar em ritmo tolerado por intervalo curto; observar resposta; pausar; repetir ou encerrar conforme planejado.','Desenvolver tolerância à locomoção e confiança em atividade graduada.','Deslocamento doméstico e comunitário.','cronômetro; dispositivo se indicado','Básica','marcha','caminhada intervalada lombalgia dor persistente condicionamento','marcha'],
['Alcance progressivo em diferentes alturas','pegar e colocar objetos','Agachar, inclinar e alcançar','quadríceps; glúteos; musculatura do core','Em pé diante de objetos leves entre a altura da cintura e uma superfície mais baixa.','Mover um objeto entre superfícies; aproximar a base; variar a altura apenas com controle e tolerância.','Praticar alcance e manuseio em amplitudes graduadas.','Organizar armários, roupas e utensílios.','objetos leves; superfícies estáveis','Intermediária','função','alcance alturas lombalgia tarefa diária','abaixar|alcançar']
);

const split = value => String(value || '').split(';').map(x=>x.trim()).filter(Boolean);
let counter = 0;
export const exercises = Object.entries(rows).flatMap(([category, list]) => list.map(row => {
  const [name,synonyms,movement,primary,start,action,objective,functional,equipment,difficulty,doseType,tags,problems] = row;
  const p = presets[category];
  return {
    id:`ex-${String(++counter).padStart(3,'0')}`,name,synonyms:split(synonyms),category,region:p.region,joint:movement || p.joint,
    primaryMuscles:split(primary),auxiliaryMuscles:split(p.aux),startPosition:start,
    steps:[`Prepare a posição: ${start}`,action,'Retorne de forma controlada, reorganize a postura e reavalie a resposta antes de repetir.'],
    objective,capacities:split(p.capacity),functionalApplication:functional,equipment:split(equipment),side:'Bilateral ou unilateral conforme a tarefa, a avaliação e o objetivo.',difficulty,
    exampleDose:dose[doseType],doseNotes:'Exemplo para discussão educacional, não uma prescrição. Ajustar volume, intensidade, descanso, amplitude e assistência à avaliação, aos objetivos e à resposta durante e após a atividade.',
    progressions:[p.progression,`Tornar a tarefa mais próxima de: ${functional}`],regressions:[p.regression],
    commonCompensations:split(p.compensation),commonErrors:['Executar rápido a ponto de perder controle.','Manter a tarefa apesar de piora relevante da qualidade ou da resposta.'],
    care:'Confirmar ambiente, equipamento, apoio e nível de assistência. Considerar restrições, precauções e orientações já estabelecidas para a pessoa.',
    stopWhen:'Interromper e reavaliar diante de dor nova ou crescente não tolerável, tontura, mal-estar, falta de ar desproporcional, perda de segurança, alteração neurológica nova ou qualquer resposta preocupante.',
    clinicalNotes:category==='Neuro'?'O rótulo diagnóstico é apenas um filtro de consulta. Selecionar pela função, estágio, cognição, comunicação, tônus, fadiga, dispositivos e nível de assistência avaliados.':category==='Pediatria'?'Individualizar conforme idade, desenvolvimento, interesses, comunicação, contexto familiar e segurança. A brincadeira deve ser significativa e não forçada.':'Observar qualidade, sintomas, confiança, fadiga e transferência para a meta funcional; documentar a resposta individual.',
    why:[objective,functional,`Pode permitir observar e treinar ${p.capacity}.`],tags:split(`${tags};${category};${p.region}`),problems:split(problems),source:`${AUTHOR_SOURCE} ${WHO_SOURCE}${String(tags).includes('lombalgia')?' '+LOW_BACK_SOURCE:''}${category==='Cardiorrespiratória'?' '+CARDIOPULM_SOURCE:''}`,kind:category==='Neuro'?'neuro':'exercise'
  };
}));

export const exerciseCount = exercises.length;
