import { downloadCategories, downloadMaterials } from './downloads-data.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const normalized=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const coverTheme=category=>{const key=normalized(category);if(key.includes('anatom'))return ['anatomy','◉'];if(key.includes('ortop')||key.includes('traumato'))return ['ortho','⌁'];if(key.includes('neuro'))return ['neuro','✦'];if(key.includes('exercicio')||key.includes('cinesio'))return ['movement','↗'];if(key.includes('avali')||key.includes('teste'))return ['assessment','✓'];if(key.includes('cardio')||key.includes('respira'))return ['cardio','♡'];return ['clinical','✚'];};

export function downloadsPage(query='',category='Todos'){
  const needle=normalized(query),rows=downloadMaterials.filter(item=>(category==='Todos'||item.category===category)&&normalized(`${item.name} ${item.category}`).includes(needle));
  const chips=downloadCategories.map(value=>`<button type="button" class="download-chip ${value===category?'active':''}" data-action="download-category" data-category="${esc(value)}">${esc(value)}<small>${value==='Todos'?downloadMaterials.length:downloadMaterials.filter(item=>item.category===value).length}</small></button>`).join('');
  const cards=rows.map((item,index)=>{const [theme,icon]=coverTheme(item.category);return `<article class="download-card ${item.restricted?'restricted':''}"><div class="download-cover cover-${theme}" aria-hidden="true"><span>${String(index+1).padStart(2,'0')}</span><i>${icon}</i><b>${esc(item.category)}</b><strong>PDF</strong></div><div class="download-copy"><div class="download-meta"><span>${esc(item.category)}</span>${item.restricted?'<em>ACESSO RESTRITO</em>':'<em class="available">DISPONÍVEL</em>'}</div><h2>${esc(item.name)}</h2><p>${item.restricted?'Este arquivo ainda exige autorização do proprietário no Google Drive.':'Material externo organizado para consulta e estudo.'}</p><div class="download-actions"><a class="button ghost" href="${esc(item.viewUrl)}" target="_blank" rel="noopener noreferrer">Visualizar</a><a class="button primary" href="${esc(item.downloadUrl)}" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">⇩</span> Baixar</a></div></div></article>`}).join('');
  return `<section class="downloads-hero"><div class="downloads-hero-art" aria-hidden="true"><span>PDF</span><i></i><i></i></div><div><small>ACERVO PARA ESTUDO</small><h1>Downloads</h1><p>Livros, atlas e materiais organizados para encontrar rápido no celular.</p><div class="downloads-hero-count"><b>${downloadMaterials.length}</b><span>materiais<br>catalogados</span></div></div></section><section class="downloads-discover"><label class="downloads-search"><span>⌕</span><input id="downloads-search" type="search" value="${esc(query)}" placeholder="Busque por título ou assunto" aria-label="Buscar material"></label><div class="download-chips" aria-label="Categorias">${chips}</div></section><div class="downloads-summary"><span><strong>${rows.length}</strong> ${rows.length===1?'material':'materiais'}</span><small>${category==='Todos'?'Todas as categorias':esc(category)}</small></div><div class="download-grid">${cards||'<div class="empty"><div class="empty-icon">⌕</div><h3>Nenhum material encontrado</h3><p>Tente outro termo ou escolha outra categoria.</p></div>'}</div><div class="downloads-note"><span aria-hidden="true">ⓘ</span><div><strong>Arquivos externos</strong><p>O Fisio Clínico organiza os links fornecidos. Disponibilidade, permissão e direitos de acesso continuam sob responsabilidade dos proprietários no Google Drive.</p></div></div>`;
}
