const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const learningTools=[
  ['escrita','Professor de escrita','Transforme anotações em evolução curta, SOAP, avaliação inicial, encaminhamento ou apresentação de caso.','✎'],
  ['agora','O que faço agora?','Receba um roteiro simples para a fase atual do atendimento.','→'],
  ['simulador','Simulador de atendimento','Converse com um paciente fictício e descubra o que esqueceu de perguntar.','◉'],
  ['raciocinio','Explicador de raciocínio','Entenda por que considerar uma avaliação e o que ela não conclui.','◇'],
  ['primeira-sessao','Montador da primeira sessão','Organize uma proposta conservadora para discutir com o supervisor.','＋'],
  ['tradutor','Tradutor para escrita clínica','Converta linguagem comum em alternativas objetivas sem inventar achados.','Aa'],
  ['prova','Modo prova prática','Resolva casos curtos e receba feedback do que precisa estudar.','✓']
];
const patientSelect=(state,id='')=>`<label class="field"><span>Vincular a um paciente (opcional)</span><select name="patientId"><option value="">Não vincular</option>${state.patients.filter(p=>!p.archived).map(p=>`<option value="${esc(p.id)}" ${p.id===id?'selected':''}>${esc(p.code||p.name)}</option>`).join('')}</select></label>`;
const area=(label,name,value='',placeholder='')=>`<label class="field"><span>${label}</span><textarea name="${name}" rows="7" placeholder="${esc(placeholder)}">${esc(value)}</textarea></label>`;
const consent='';
const modeMap={escrita:'writing',agora:'next',raciocinio:'reasoning','primeira-sessao':'session',tradutor:'translate'};
function resultView(result){if(!result)return '';return `<section class="panel learning-result"><span class="eyebrow">RESULTADO EDUCACIONAL</span><h2>${esc(result.title)}</h2><div class="primary-output">${esc(result.primaryOutput)}</div>${result.score?`<div class="learning-score"><strong>${result.score}</strong><span>pontuação educacional</span></div>`:''}${result.sections.map(s=>`<article class="learning-section"><h3>${esc(s.title)}</h3>${s.content?`<p>${esc(s.content)}</p>`:''}${s.items.length?`<ul>${s.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`:''}</article>`).join('')}${result.improvements.length?`<article class="learning-section"><h3>O que melhorou / pontos fortes</h3><ul>${result.improvements.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></article>`:''}${result.questions.length?`<article class="learning-section"><h3>O que ainda perguntar ou estudar</h3><ul>${result.questions.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></article>`:''}${result.cautions.length?`<div class="advisory"><span class="advisory-icon">ⓘ</span><div><strong>Cuidados</strong><ul>${result.cautions.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></div></div>`:''}<button class="button secondary full" type="button" data-action="copy-learning-result">Copiar resultado</button></section>`;}
export function learningHub(){return `<div class="learning-hero"><span>APRENDER NA PRÁTICA</span><h1>Qual ajuda você precisa agora?</h1><p>Escolha uma ferramenta. Você pode escrever ou tocar no microfone para falar.</p></div><a href="#mentor" class="learning-tool-card mentor-featured"><b>✦</b><span><strong>Mentor Clínico completo</strong><small>Conte o caso e receba escrita, avaliações, condutas e exercícios explicados.</small></span><i>→</i></a><div class="learning-tool-grid">${learningTools.map(([id,title,desc,icon])=>`<a href="#aprender/${id}" class="learning-tool-card"><b>${icon}</b><span><strong>${title}</strong><small>${desc}</small></span><i>→</i></a>`).join('')}</div>`;}
export function learningToolPage(state,tool,draft={}){const meta=learningTools.find(x=>x[0]===tool);if(!meta)return learningHub();const common=`<input type="hidden" name="tool" value="${tool}">${patientSelect(state,draft.patientId)}${consent}`,value=draft.input||'';let fields='',mode=modeMap[tool]||tool;
  if(tool==='escrita')fields=`<label class="field"><span>Formato</span><select name="format"><option>Evolução curta</option><option>SOAP</option><option>Avaliação inicial</option><option>Encaminhamento</option><option>Apresentação de caso</option></select></label>${area('Anotações brutas','input',value,'Cole apenas fatos observados ou relatados...')}`;
  if(tool==='agora')fields=`<label class="field"><span>Fase do atendimento</span><select name="phase"><option>Anamnese</option><option>Exame físico</option><option>Escolha de testes</option><option>Definição de objetivos</option><option>Planejamento da sessão</option><option>Reavaliação</option></select></label>${area('O que você já sabe','input',value,'Descreva o caso e onde você travou...')}`;
  if(tool==='raciocinio')fields=`${area('Caso e sugestão que você quer entender','input',value,'Ex.: pensei em usar o TUG; o que ele responde e o que não conclui?')}`;
  if(tool==='primeira-sessao')fields=`<div class="form-grid"><label class="field"><span>Tempo disponível</span><input name="duration" placeholder="Ex.: 40 minutos"></label><label class="field"><span>Equipamentos</span><input name="equipment" placeholder="Ex.: cadeira, parede e faixa"></label></div>${area('Caso e objetivo','input',value,'Inclua somente informações conhecidas e restrições já estabelecidas...')}`;
  if(tool==='tradutor')fields=`${area('Como você falaria normalmente','input',value,'Ex.: ela anda meio torta e cansa rápido...')}`;
  if(tool==='simulador'){mode=draft.result?'simulation-reply':'simulation-start';fields=draft.result?`<div class="simulation-chat">${(draft.history||[]).map(m=>`<p class="${m.role}">${esc(m.content)}</p>`).join('')}<p class="assistant">${esc(draft.result.primaryOutput)}</p></div>${area('Sua próxima pergunta','input','','Pergunte como se estivesse atendendo...')}`:`<div class="form-grid"><label class="field"><span>Área</span><select name="area"><option>Ortopedia</option><option>Neurologia</option><option>Geriatria</option><option>Cardiorrespiratória</option><option>Saúde da mulher</option><option>Pediatria</option></select></label><label class="field"><span>Dificuldade</span><select name="difficulty"><option>Iniciante</option><option>Intermediária</option></select></label></div>`;}
  if(tool==='prova'){mode=draft.result?'exam-grade':'exam-generate';fields=draft.result?`<div class="exam-case"><strong>Caso</strong><p>${esc(draft.result.primaryOutput)}</p></div>${area('Sua resposta','input','','Explique o que avaliaria, riscos, registro e conduta para discussão...')}`:`<label class="field"><span>Nível</span><select name="difficulty"><option>Primeiro estágio</option><option>Intermediário</option></select></label>`;}
  return `<div class="back"><a href="#aprender">← Ferramentas de aprendizagem</a></div><div class="page-head"><div><span class="eyebrow">${esc(meta[1])}</span><h1>${esc(meta[1])}</h1><p>${esc(meta[2])}</p></div></div><form id="learning-tool-form" class="panel"><input type="hidden" name="mode" value="${mode}">${fields}${common}<div class="mobile-sticky-action"><button class="button primary full" type="submit">${draft.loading?'Preparando…':tool==='simulador'&&draft.result?'Enviar pergunta':tool==='prova'&&draft.result?'Corrigir resposta':'Gerar ajuda'}</button>${tool==='simulador'&&draft.result?'<button class="button ghost full" type="button" data-action="finish-simulation">Encerrar e receber feedback</button>':''}${(tool==='simulador'||tool==='prova')&&draft.result?'<button class="button ghost full" type="button" data-action="reset-learning-tool">Começar novamente</button>':''}</div></form>${!['simulador','prova'].includes(tool)?resultView(draft.result):draft.finished?resultView(draft.result):''}`;}
