export const palpationGuides = [
  ['trapézio superior','Cervical e cintura escapular','Sentado, ombros relaxados e cabeça em posição confortável.','Processo espinhoso de C7, acrômio e região occipital.','Elevar suavemente o ombro contra resistência leve.','Percorra a massa muscular entre cervical e acrômio com polpas digitais, comparando textura e resposta entre os lados.','Evite pressão sobre estruturas vasculonervosas e não interprete sensibilidade isolada como diagnóstico.'],
  ['esternocleidomastoideo','Cervical','Sentado ou em decúbito, com apoio para a cabeça.','Processo mastoide, manúbrio e terço medial da clavícula.','Girar a cabeça para o lado oposto e realizar leve flexão cervical.','Identifique as duas porções entre mastoide, esterno e clavícula; use pinça suave apenas quando apropriado.','Palpação anterior do pescoço exige cuidado; evite compressão carotídea.'],
  ['deltoide','Ombro','Sentado, braço apoiado e ombro relaxado.','Acrômio, espinha da escápula e tuberosidade deltoidea.','Iniciar abdução ou flexão do ombro com resistência mínima.','Palpe as porções anterior, média e posterior da massa muscular ao redor do ombro.','Diferencie músculo, tendão e referências ósseas; respeite dor e restrições pós-operatórias.'],
  ['peitoral maior','Tórax e ombro','Decúbito ou sentado, com consentimento e exposição mínima necessária.','Clavícula, esterno e prega axilar anterior.','Aduzir horizontalmente o braço contra resistência leve.','Acompanhe as fibras em direção ao úmero sem pressionar tecido mamário.','Privacidade, consentimento explícito e presença de acompanhante quando indicado são essenciais.'],
  ['bíceps braquial','Braço anterior','Sentado, cotovelo apoiado e antebraço em supinação.','Sulco intertubercular, região anterior do braço e fossa cubital.','Flexionar o cotovelo com supinação contra resistência leve.','Palpe o ventre no braço e, distalmente, o tendão com pressão suave.','Não force a fossa cubital; alterações tendíneas exigem correlação com história e exame.'],
  ['tríceps braquial','Braço posterior','Sentado ou decúbito, ombro e cotovelo apoiados.','Região posterior do úmero e olécrano.','Estender o cotovelo contra resistência leve.','Palpe o ventre posterior e acompanhe o tendão até o olécrano.','Evite comprimir o nervo ulnar no sulco medial do cotovelo.'],
  ['extensores de punho','Antebraço','Antebraço apoiado, mão fora da borda e dedos relaxados.','Epicôndilo lateral e dorso do antebraço.','Estender o punho com leve desvio radial contra resistência.','Acompanhe a massa extensora a partir do epicôndilo em direção ao punho.','Dor à palpação não identifica isoladamente a estrutura responsável.'],
  ['eretores da espinha','Coluna','Sentado ou em decúbito ventral confortável.','Processos espinhosos e massas paravertebrais.','Realizar extensão suave do tronco ou manter postura ereta.','Palpe longitudinalmente as massas musculares, sem pressão direta intensa sobre processos espinhosos.','Interrompa diante de piora importante, sintomas irradiados ou desconforto não esperado.'],
  ['glúteo máximo','Quadril posterior','Decúbito ventral ou lateral, com drapejamento adequado.','Crista ilíaca, sacro e tuberosidade isquiática.','Estender o quadril com joelho flexionado, em amplitude confortável.','Palpe a massa glútea no quadrante seguro, relacionando a ativação ao movimento.','Consentimento, privacidade e respeito às referências de injeção e ao trajeto do ciático.'],
  ['glúteo médio','Quadril lateral','Decúbito lateral, lado avaliado para cima e pelve estável.','Crista ilíaca e trocânter maior.','Abduzir suavemente o quadril sem rodar o tronco.','Palpe abaixo da crista ilíaca, superiormente ao trocânter maior.','Controle compensações e não conclua fraqueza apenas pela palpação.'],
  ['reto femoral','Coxa anterior','Decúbito dorsal ou sentado, joelho apoiado.','Espinha ilíaca anteroinferior, centro da coxa e patela.','Estender o joelho ou flexionar o quadril contra resistência leve.','Palpe o ventre central da coxa durante ativação breve e relaxamento.','Considere edema, trauma, pós-operatório e tolerância antes de aplicar pressão.'],
  ['vasto medial','Joelho e coxa','Decúbito dorsal, joelho apoiado em leve flexão.','Borda superomedial da patela e terço distal medial da coxa.','Realizar extensão terminal suave do joelho.','Observe e palpe a ativação acima e medialmente à patela.','O momento visual de ativação isolado não determina disfunção patelofemoral.'],
  ['isquiotibiais','Coxa posterior','Decúbito ventral, joelho em leve flexão.','Tuberosidade isquiática, região posterior da coxa e fossa poplítea.','Flexionar o joelho contra resistência leve; rotação pode ajudar a diferenciar tendões.','Palpe os ventres posterior-medial e posterior-lateral, sem comprimir a fossa poplítea.','Evite pressão profunda na fossa poplítea e respeite suspeita de lesão aguda.'],
  ['tibial anterior','Perna anterior','Sentado ou decúbito, perna apoiada e tornozelo livre.','Côndilo lateral da tíbia, borda lateral da tíbia e dorso medial do pé.','Dorsifletir e inverter suavemente o pé.','Palpe lateralmente à crista tibial e acompanhe o tendão no tornozelo.','Não confunda o bordo ósseo da tíbia com o ventre muscular.'],
  ['gastrocnêmio e sóleo','Panturrilha','Decúbito ventral ou em pé com apoio, conforme segurança.','Côndilos femorais, massa da panturrilha e tendão calcâneo.','Fazer flexão plantar; com joelho flexionado, aumenta-se a participação relativa do sóleo.','Palpe as cabeças do gastrocnêmio e a região mais profunda/lateral do sóleo com suavidade.','Não realize compressão vigorosa diante de edema súbito, calor, rubor ou suspeita vascular.']
].map(([name,region,position,landmarks,confirmation,palpation,caution],index)=>({id:`palp-${index+1}`,name,region,position,landmarks,confirmation,palpation,caution}));
