const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const area=(label,name,placeholder='')=>`<label class="field rapid-field-card"><span>${label}</span><textarea name="${name}" rows="2" placeholder="${placeholder}"></textarea></label>`;
const lastFor=(state,id)=>state.quickCareSessions.filter(row=>row.patientId===id).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''))[0]||state.sessions.filter(row=>row.patientId===id).sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0];

export function buildRapidEvolution(v){return [`Atendimento em ${v.date}.`,v.focus&&`Queixa/foco: ${v.focus}.`,v.painScore!==''&&v.painScore!=null&&`Dor referida: ${v.painScore}/10.`,v.vitals&&`Sinais vitais: ${v.vitals}.`,v.pain&&`Dor: ${v.pain}.`,v.rom&&`ADM: ${v.rom}.`,v.strength&&`Força: ${v.strength}.`,v.balance&&`Equilíbrio: ${v.balance}.`,v.gait&&`Marcha: ${v.gait}.`,v.exercise&&`Realizado: ${v.exercise}.`,v.test&&`Teste/medida: ${v.test}.`,v.responseKind&&`Resposta observada: ${v.responseKind}.`,v.response&&`Resposta: ${v.response}.`,v.observation&&`Observações: ${v.observation}.`].filter(Boolean).join(' ');}

const painScale=()=>`<fieldset class="rapid-field-card"><legend>Dor <small>(escala numérica)</small></legend><p>Como o paciente refere a dor hoje?</p><div class="pain-scale">${Array.from({length:11},(_,i)=>`<label><input type="radio" name="painScore" value="${i}"><span>${i}</span></label>`).join('')}</div><div class="pain-scale-legend"><span>Sem dor</span><span>Pior dor possível</span></div></fieldset>`;
const responseOptions=()=>`<div class="response-options">${[['Melhorou','better'],['Manteve','same'],['Piorou','worse'],['Sem alteração','neutral']].map(([label,tone])=>`<label class="${tone}"><input type="radio" name="responseKind" value="${label.toLowerCase()}"><span>${label}</span></label>`).join('')}</div>`;
const advancedFields=(state,id)=>{const last=lastFor(state,id);return `<details class="rapid-advanced"><summary>Mais dados do atendimento</summary><div class="rapid-advanced-body"><div class="last-summary"><strong>Resumo de 30 segundos</strong><p>${esc(last?.evolutionDetailed||last?.summary||last?.interventions||'Sem sessão anterior.')}</p></div><fieldset><legend>Checklist pré-atendimento</legend>${['Dor atual','Queda recente','Tontura','Mudança dos sintomas','Medicação nova','PA quando indicada','Restrição médica/pós-operatória','Intercorrências'].map((x,i)=>`<label><input type="checkbox" name="check${i}"> ${x}</label>`).join('')}</fieldset><fieldset class="body-map"><legend>Mapa corporal de dor</legend><p>Toque nas regiões e registre apenas o relato.</p><div class="rapid-buttons">${['cervical','ombro D','ombro E','torácica','lombar','quadril D','quadril E','joelho D','joelho E','perna/pé D','perna/pé E'].map(region=>`<label><input type="checkbox" name="painRegion" value="${region}"> ${region}</label>`).join('')}</div><div class="rapid-buttons">${['queimação','pontada','peso','formigamento','irradiada'].map(kind=>`<label><input type="checkbox" name="painCharacteristic" value="${kind}"> ${kind}</label>`).join('')}</div><label class="field"><span>Irradiação após movimento/tarefa</span><select name="irradiationChange"><option value="">Não registrado</option><option>mais proximal (centralizou)</option><option>mais distal (periferizou)</option><option>sem mudança</option></select></label></fieldset><div class="rapid-buttons"><button type="button" data-action="rapid-preset" data-target="pain">Dor</button><button type="button" data-action="rapid-preset" data-target="vitals">PA · FC · SpO₂</button><button type="button" data-action="rapid-preset" data-target="rom">ADM</button><button type="button" data-action="rapid-preset" data-target="strength">Força</button><button type="button" data-action="rapid-preset" data-target="balance">Equilíbrio</button><button type="button" data-action="rapid-preset" data-target="gait">Marcha</button></div><div class="form-grid">${area('Dor antes/depois','pain','Ex.: antes 6/10; depois 4/10')}${area('PA, FC e SpO₂','vitals','Ex.: PA inicial 130/80; final 128/78')}${area('ADM bilateral','rom','D: … | E: …')}${area('Força bilateral','strength','D: … | E: …')}${area('Equilíbrio','balance')}${area('Marcha','gait')}${area('Teste','test')}</div><div class="timer-presets"><strong>Temporizador</strong>${[30,45,60,120,300].map(s=>`<button type="button" data-action="rapid-timer" data-seconds="${s}">${s<60?s+' s':s/60+' min'}</button>`).join('')}<output class="rapid-timer-output">00:00</output></div>${area('★ Perguntar ao supervisor','supervisorQuestion','A dúvida será destacada no registro.')}</div></details>`;};

const patientIdentity=(p,label)=>`<div class="rapid-patient-identity"><span class="patient-avatar">${esc((p.code||p.name||label).slice(0,2).toUpperCase())}</span><div><small>${label}</small><strong>${esc(p.code||p.name)}</strong><span>${esc(p.area||p.specialty||'Paciente selecionado')}</span></div></div>`;
const pane=(state,id,label,{standalone=false}={})=>{const p=state.patients.find(x=>x.id===id);if(!p)return '';return `<form class="rapid-pane" id="rapid-care-form-${esc(id)}" data-patient="${esc(id)}">${patientIdentity(p,label)}<input type="hidden" name="patientId" value="${esc(id)}"><section class="rapid-field-card"><label class="field"><span>Data do atendimento</span><input type="date" name="date" value="${new Date().toLocaleDateString('sv-SE')}"></label></section>${area('Queixa ou foco de hoje','focus','Descreva a queixa principal ou o foco do atendimento de hoje...')}${painScale()}<section class="rapid-field-card"><h3>Exercício ou conduta</h3><div class="conduct-chips">${['Exercícios terapêuticos','Mobilização','Alongamento','Orientações','Eletroterapia','Outro'].map(item=>`<button type="button" data-action="rapid-conduct" data-value="${item}">${item}</button>`).join('')}</div><label class="field"><span>O que foi realizado?</span><textarea name="exercise" rows="3" placeholder="Descreva os exercícios, técnicas ou condutas realizadas hoje..."></textarea></label></section><section class="rapid-field-card"><h3>Resposta do paciente</h3>${responseOptions()}<label class="field"><span>Resposta observada</span><textarea name="response" rows="2" placeholder="Como o paciente reagiu ao atendimento?"></textarea></label></section>${area('Observação','observation','Registre apenas o que foi observado.')}${advancedFields(state,id)}${standalone?'<button class="button primary full rapid-single-save" type="submit">Salvar atendimento</button>':''}</form>`;};
const patientOptions=(state,current='')=>state.patients.filter(p=>!p.archived).map(p=>`<option value="${esc(p.id)}" ${p.id===current?'selected':''}>${esc(p.code||p.name)}</option>`).join('');
const picker=(state,a,b,mode)=>`<section class="rapid-patient-picker"><div><strong>${mode==='duplo'?'Selecione os pacientes':'Selecione o paciente'}</strong><p>${mode==='duplo'?'Escolha até 2 participantes para registrar o atendimento de forma rápida.':'Escolha quem será atendido para iniciar o registro.'}</p></div><label>Paciente A<select id="rapid-a"><option value="">Selecione</option>${patientOptions(state,a)}</select></label>${mode==='duplo'?`<label>Paciente B <small>(opcional)</small><select id="rapid-b"><option value="">Adicionar depois</option>${patientOptions(state,b)}</select></label>`:''}<button class="button secondary full" type="button" data-action="open-rapid-patients" data-mode="${mode}">${a?'Atualizar seleção':'Iniciar atendimento'}</button></section>`;

export function rapidCarePage(state,a='',b='',mode='individual'){
  const dual=mode==='duplo';
  const title=dual?'Atendimento rápido':'Novo atendimento';
  return `<div class="rapid-care-page"><div class="page-head rapid-page-head"><div><span class="eyebrow">ATENDER</span><h1>${title}</h1><p>${dual?'Registre até dois pacientes da prática supervisionada.':'Registre a evolução de um paciente com rapidez.'}</p></div></div><nav class="rapid-mode-switch" aria-label="Modo de atendimento"><a class="${!dual?'active':''}" href="#atendimento-rapido?mode=individual">Um paciente</a><a class="${dual?'active':''}" href="#atendimento-rapido?mode=duplo">Dois pacientes</a></nav>${picker(state,a,b,mode)}${a?`<div class="rapid-grid ${dual?'is-dual':'is-single'}">${pane(state,a,dual?'PACIENTE A':'PACIENTE SELECIONADO',{standalone:!dual})}${dual&&b?pane(state,b,'PACIENTE B'):dual?'<section class="rapid-add-patient"><strong>Paciente B (opcional)</strong><p>Selecione acima para adicionar o segundo registro.</p></section>':''}</div>${dual?'<div class="rapid-save-bar"><button class="button primary full" type="button" data-action="save-rapid-all">Salvar registros</button></div>':''}`:''}</div>`;
}
