const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const area=(label,name,placeholder='')=>`<label class="field rapid-field-card"><span>${label}</span><textarea name="${name}" rows="2" placeholder="${placeholder}"></textarea></label>`;
const lastFor=(state,id)=>state.quickCareSessions.filter(row=>row.patientId===id).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''))[0]||state.sessions.filter(row=>row.patientId===id).sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0];
const avatarIndex=patient=>[...String(patient?.id||patient?.code||patient?.name||'paciente')].reduce((sum,char)=>sum+char.charCodeAt(0),0)%6;

export function buildRapidEvolution(v){return [`Atendimento em ${v.date}.`,v.focus&&`Queixa/foco: ${v.focus}.`,v.painScore!==''&&v.painScore!=null&&`Dor referida: ${v.painScore}/10.`,v.vitals&&`Sinais vitais: ${v.vitals}.`,v.pain&&`Dor: ${v.pain}.`,v.rom&&`ADM: ${v.rom}.`,v.strength&&`Força: ${v.strength}.`,v.balance&&`Equilíbrio: ${v.balance}.`,v.gait&&`Marcha: ${v.gait}.`,v.exercise&&`Realizado: ${v.exercise}.`,v.test&&`Teste/medida: ${v.test}.`,v.responseKind&&`Resposta observada: ${v.responseKind}.`,v.response&&`Resposta: ${v.response}.`,v.observation&&`Observações: ${v.observation}.`].filter(Boolean).join(' ');}

const painScale=()=>`<fieldset class="rapid-field-card"><legend>Dor <small>(escala numérica)</small></legend><p>Como o paciente refere a dor hoje?</p><div class="pain-scale">${Array.from({length:11},(_,i)=>`<label><input type="radio" name="painScore" value="${i}"><span>${i}</span></label>`).join('')}</div><div class="pain-scale-legend"><span>Sem dor</span><span>Pior dor possível</span></div></fieldset>`;
const responseOptions=()=>`<div class="response-options">${[['Melhorou','better'],['Manteve','same'],['Piorou','worse'],['Sem alteração','neutral']].map(([label,tone])=>`<label class="${tone}"><input type="radio" name="responseKind" value="${label.toLowerCase()}"><span>${label}</span></label>`).join('')}</div>`;
const advancedFields=(state,id)=>{const last=lastFor(state,id);return `<details class="rapid-advanced"><summary>Mais dados do atendimento</summary><div class="rapid-advanced-body"><div class="last-summary"><strong>Resumo de 30 segundos</strong><p>${esc(last?.evolutionDetailed||last?.summary||last?.interventions||'Sem sessão anterior.')}</p></div><fieldset><legend>Checklist pré-atendimento</legend>${['Dor atual','Queda recente','Tontura','Mudança dos sintomas','Medicação nova','PA quando indicada','Restrição médica/pós-operatória','Intercorrências'].map((x,i)=>`<label><input type="checkbox" name="check${i}"> ${x}</label>`).join('')}</fieldset><fieldset class="body-map"><legend>Mapa corporal de dor</legend><p>Toque nas regiões e registre apenas o relato.</p><div class="rapid-buttons">${['cervical','ombro D','ombro E','torácica','lombar','quadril D','quadril E','joelho D','joelho E','perna/pé D','perna/pé E'].map(region=>`<label><input type="checkbox" name="painRegion" value="${region}"> ${region}</label>`).join('')}</div><div class="rapid-buttons">${['queimação','pontada','peso','formigamento','irradiada'].map(kind=>`<label><input type="checkbox" name="painCharacteristic" value="${kind}"> ${kind}</label>`).join('')}</div><label class="field"><span>Irradiação após movimento/tarefa</span><select name="irradiationChange"><option value="">Não registrado</option><option>mais proximal (centralizou)</option><option>mais distal (periferizou)</option><option>sem mudança</option></select></label></fieldset><div class="rapid-buttons"><button type="button" data-action="rapid-preset" data-target="pain">Dor</button><button type="button" data-action="rapid-preset" data-target="vitals">PA · FC · SpO₂</button><button type="button" data-action="rapid-preset" data-target="rom">ADM</button><button type="button" data-action="rapid-preset" data-target="strength">Força</button><button type="button" data-action="rapid-preset" data-target="balance">Equilíbrio</button><button type="button" data-action="rapid-preset" data-target="gait">Marcha</button></div><div class="form-grid">${area('Dor antes/depois','pain','Ex.: antes 6/10; depois 4/10')}${area('PA, FC e SpO₂','vitals','Ex.: PA inicial 130/80; final 128/78')}${area('ADM bilateral','rom','D: … | E: …')}${area('Força bilateral','strength','D: … | E: …')}${area('Equilíbrio','balance')}${area('Marcha','gait')}${area('Teste','test')}</div><div class="timer-presets"><strong>Temporizador</strong>${[30,45,60,120,300].map(s=>`<button type="button" data-action="rapid-timer" data-seconds="${s}">${s<60?s+' s':s/60+' min'}</button>`).join('')}<output class="rapid-timer-output">00:00</output></div>${area('★ Perguntar ao supervisor','supervisorQuestion','A dúvida será destacada no registro.')}</div></details>`;};

const patientIdentity=(state,p,label)=>{const last=lastFor(state,p.id);return `<div class="rapid-patient-identity"><span class="patient-avatar patient-chibi chibi-${avatarIndex(p)}" role="img" aria-label="Avatar ilustrado"></span><div><small>${label}</small><strong>${esc(p.code||p.name)}</strong><span>${esc(p.chiefComplaint||p.focus||p.area||'Paciente selecionado')}</span></div>${last?'<span class="rapid-returning">Com histórico</span>':''}</div>`;};
const pane=(state,id,label,{standalone=false}={})=>{const p=state.patients.find(x=>x.id===id);if(!p)return '';return `<form class="rapid-pane" id="rapid-care-form-${esc(id)}" data-patient="${esc(id)}">${patientIdentity(state,p,label)}<div class="rapid-form-guide"><span>Registre o essencial</span><small>Preencha somente o que foi observado ou realizado.</small></div><input type="hidden" name="patientId" value="${esc(id)}"><section class="rapid-field-card rapid-date-card"><label class="field"><span>Data do atendimento</span><input type="date" name="date" value="${new Date().toLocaleDateString('sv-SE')}"></label></section>${area('Queixa ou foco de hoje','focus','Descreva a queixa principal ou o foco do atendimento de hoje...')}${painScale()}<section class="rapid-field-card"><h3>Exercício ou conduta</h3><p>Marque uma categoria e descreva apenas o que foi realizado.</p><div class="conduct-chips">${['Exercícios terapêuticos','Mobilização','Alongamento','Orientações','Eletroterapia','Outro'].map(item=>`<button type="button" data-action="rapid-conduct" data-value="${item}" aria-pressed="false">${item}</button>`).join('')}</div><label class="field"><span>O que foi realizado?</span><textarea name="exercise" rows="3" placeholder="Exercícios, técnicas, séries, repetições ou adaptações..."></textarea></label></section><section class="rapid-field-card"><h3>Resposta do paciente</h3><p>Selecione a resposta geral e complemente quando necessário.</p>${responseOptions()}<label class="field"><span>Resposta observada</span><textarea name="response" rows="2" placeholder="Tolerância, sintomas, pausas, ajuda ou modificações..."></textarea></label></section>${area('Observação','observation','Intercorrências ou outra informação relevante.')}${advancedFields(state,id)}${standalone?'<button class="button primary full rapid-single-save" type="submit">Salvar atendimento</button>':''}</form>`;};
const patientOptions=(state,current='')=>state.patients.filter(p=>!p.archived).map(p=>`<option value="${esc(p.id)}" ${p.id===current?'selected':''}>${esc(p.code||p.name)} — ${esc(p.chiefComplaint||p.focus||'sem foco registrado')}</option>`).join('');
const selectCard=(state,current,id,label,optional=false)=>{const patient=state.patients.find(p=>p.id===current);return `<label class="rapid-select-card" for="${id}"><span class="rapid-select-avatar ${patient?`patient-chibi chibi-${avatarIndex(patient)}`:''}">${patient?'':label.slice(-1)}</span><span class="rapid-select-copy"><small>${label}${optional?' · opcional':''}</small><select id="${id}"><option value="">${optional?'Adicionar depois':'Toque para selecionar'}</option>${patientOptions(state,current)}</select></span><b aria-hidden="true">⌄</b></label>`;};
const picker=(state,a,b,mode)=>`<section class="rapid-patient-picker"><div class="rapid-picker-intro"><span class="rapid-picker-icon">⌁</span><span><strong>${mode==='duplo'?'Quem será atendido?':'Selecione o paciente'}</strong><p>${mode==='duplo'?'Escolha o primeiro paciente e, se necessário, adicione o segundo.':'Escolha um acompanhamento para iniciar o registro.'}</p></span></div><div class="rapid-picker-selects">${selectCard(state,a,'rapid-a','Paciente A')}${mode==='duplo'?selectCard(state,b,'rapid-b','Paciente B',true):''}</div><button class="button primary full" type="button" data-action="open-rapid-patients" data-mode="${mode}">Continuar para o registro</button></section>`;
const selectionSummary=(state,a,b,mode)=>{const patients=[a,b].filter(Boolean).map(id=>state.patients.find(p=>p.id===id)).filter(Boolean);return `<section class="rapid-selection-summary"><div class="rapid-selection-people">${patients.map((p,index)=>`<span><i>${esc((p.code||p.name).slice(0,2).toUpperCase())}</i><span><small>${mode==='duplo'?`PACIENTE ${index?'B':'A'}`:'PACIENTE'}</small><strong>${esc(p.code||p.name)}</strong></span></span>`).join('')}</div><a href="#atendimento-rapido?mode=${mode}">${mode==='duplo'&&!b?'Adicionar ou trocar pacientes':'Trocar seleção'}</a></section>`;};

export function rapidCarePage(state,a='',b='',mode='individual'){
  const dual=mode==='duplo';
  const title=dual?'Atendimento rápido':'Novo atendimento';
  return `<div class="rapid-care-page"><header class="rapid-native-head"><span class="eyebrow">ATENDIMENTO</span><h1>${title}</h1><p>${dual?'Registre até dois pacientes sem misturar as informações.':'Registre a evolução de um paciente com rapidez.'}</p></header><nav class="rapid-mode-switch" aria-label="Modo de atendimento"><a class="${!dual?'active':''}" href="#atendimento-rapido?mode=individual"><span class="rapid-mode-icon">1</span><span><strong>Um paciente</strong><small>Registro individual</small></span></a><a class="${dual?'active':''}" href="#atendimento-rapido?mode=duplo"><span class="rapid-mode-icon">2</span><span><strong>Dois pacientes</strong><small>Registros lado a lado</small></span></a></nav>${a?selectionSummary(state,a,b,mode):picker(state,a,b,mode)}${a?`<div class="rapid-grid ${dual?'is-dual':'is-single'}">${pane(state,a,dual?'PACIENTE A':'PACIENTE SELECIONADO',{standalone:!dual})}${dual&&b?pane(state,b,'PACIENTE B'):dual?'<a class="rapid-add-patient" href="#atendimento-rapido?mode=duplo"><span>＋</span><strong>Adicionar Paciente B</strong><p>Inclua um segundo registro quando necessário.</p></a>':''}</div>${dual?'<div class="rapid-save-bar"><button class="button primary full" type="button" data-action="save-rapid-all">Salvar registros preenchidos</button></div>':''}`:''}</div>`;
}
