import { functionalTests, neuroContexts, pediatricActivities } from './v06-data.js';
import { reassessmentRows, summarizeTestVariation } from './v06-core.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const date=value=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const field=(label,name,type='text',value='',attrs='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
const area=(label,name,value='',placeholder='')=>`<label class="field"><span>${label}</span><textarea name="${name}" rows="3" placeholder="${esc(placeholder)}">${esc(value)}</textarea></label>`;
const select=(label,name,options,value='')=>`<label class="field"><span>${label}</span><select name="${name}">${options.map(([id,text])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
const header=(eyebrow,title,text)=>`<div class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${text}</p></div></div>`;
const empty=(title,text)=>`<div class="empty"><h3>${title}</h3><p>${text}</p></div>`;
const patientOptions=state=>[['','Selecione o paciente'],...state.patients.filter(row=>!row.archived).map(row=>[row.id,row.name||row.code||'Paciente'])];
const patientNav=(state,route,patientId)=>`<div class="patient-route-picker">${select('Paciente','routePatient',patientOptions(state),patientId)}<button class="button secondary" type="button" data-action="route-patient" data-route="${route}">Abrir</button></div>`;

function lineChart(rows){
  if(rows.length<2)return '';
  const values=rows.map(row=>Number(row.result)),min=Math.min(...values),max=Math.max(...values),range=max-min||1;
  const points=values.map((value,index)=>`${10+index*280/(values.length-1)},${100-(value-min)*80/range}`).join(' ');
  return `<div class="simple-chart"><svg viewBox="0 0 300 110" role="img" aria-label="Série temporal dos resultados"><line x1="10" y1="100" x2="290" y2="100"></line><polyline points="${points}"></polyline>${values.map((value,index)=>`<circle cx="${10+index*280/(values.length-1)}" cy="${100-(value-min)*80/range}" r="4"><title>${value}</title></circle>`).join('')}</svg></div>`;
}

export function functionalTestsPage(state,testId='',patientId=''){
  const test=functionalTests.find(row=>row.id===testId);
  if(!test)return `${header('MEDIDAS DE RESULTADO','Testes funcionais','Aplicação, registro e acompanhamento longitudinal separados dos testes clínicos especiais.')}<div class="functional-test-grid">${functionalTests.map(row=>`<a class="reference-card" href="#testes-funcionais/${row.id}"><span class="source-label">${esc(row.variable)}</span><h3>${esc(row.name)}</h3><p>${esc(row.objective)}</p><small>${esc(row.source)}</small></a>`).join('')}</div>`;
  const records=state.functionalTestResults.filter(row=>row.testId===test.id&&(!patientId||row.patientId===patientId)).sort((a,b)=>a.date.localeCompare(b.date));
  const variation=patientId?summarizeTestVariation(state.functionalTestResults,patientId,test.id,test.unit):null;
  return `<div class="back"><a href="#testes-funcionais">← Testes funcionais</a></div>${header('TESTE FUNCIONAL',test.name,test.objective)}${patientNav(state,`testes-funcionais/${test.id}`,patientId)}
  <div class="detail-columns"><section class="panel protocol-card"><h2>Aplicação</h2><dl><dt>Contexto</dt><dd>${esc(test.context)}</dd><dt>Materiais</dt><dd>${esc(test.materials)}</dd><dt>Preparação</dt><dd>${esc(test.preparation)}</dd><dt>Execução</dt><dd>${esc(test.execution)}</dd><dt>Variável</dt><dd>${esc(test.variable)} · ${esc(test.unit)}</dd><dt>Limitações</dt><dd>${esc(test.limitations)}</dd><dt>Fonte</dt><dd>${esc(test.source)}</dd></dl></section>
  <section class="panel"><h2>Aplicar e registrar</h2><div class="integrated-timer" data-seconds="${test.timerSeconds||0}"><strong id="test-timer">00:00.00</strong><div><button class="button primary" type="button" data-action="test-timer-start">Iniciar</button><button class="button secondary" type="button" data-action="test-timer-pause">Pausar</button><button class="button ghost" type="button" data-action="test-timer-reset">Zerar</button></div></div><form id="functional-test-form"><input type="hidden" name="testId" value="${test.id}"><input type="hidden" name="testName" value="${esc(test.name)}"><input type="hidden" name="unit" value="${esc(test.unit)}"><div class="form-grid">${select('Paciente *','patientId',patientOptions(state),patientId)}${field('Data *','date','date',new Date().toLocaleDateString('sv-SE'),'required')}${field(`Resultado (${test.unit}) *`,'result','number','','required step="0.01"')}${field('Tentativas','attempts','number','1','min="1" max="20"')}${field('Melhor tentativa','best','number','','step="0.01"')}${field('Média','average','number','','step="0.01"')}${field('Dispositivo','device')}${select('Assistência','assistance',[['','Não registrada'],['independente','Independente'],['supervisao','Supervisão'],['minima','Mínima'],['moderada','Moderada'],['maxima','Máxima']])}${test.side?select('Lado','side',[['','Não informado'],['Direito','Direito'],['Esquerdo','Esquerdo'],['Bilateral','Bilateral']]):''}</div>${area('Observações','notes','','Protocolo, adaptações, sintomas, pausas e motivo de interrupção')}<button class="button primary" type="submit">Salvar resultado</button></form></section></div>
  <section class="panel history-panel"><div class="section-title"><h2>Histórico</h2>${variation?`<span class="variation">Variação observada: ${esc(variation.label)}</span>`:''}</div>${lineChart(records)}${records.length?`<div class="history-cards">${records.map(row=>`<article><span>${date(row.date)}</span><strong>${esc(row.result)} ${esc(row.unit)}</strong><small>${esc([row.device,row.assistance,row.notes].filter(Boolean).join(' · '))}</small></article>`).join('')}</div>`:empty('Sem resultados','Selecione um paciente e salve a primeira aplicação.')}</section>`;
}

export function reassessmentPage(state,patientId=''){
  if(!patientId)return `${header('LONGITUDINAL','Reavaliação','Compare registros iniciais e atuais sem atribuir significado clínico automaticamente.')}${patientNav(state,'reavaliacao','')}`;
  const patient=state.patients.find(row=>row.id===patientId);if(!patient)return empty('Paciente não encontrado','Volte à lista de pacientes.');
  const rows=reassessmentRows(state,patientId),goals=state.goals.filter(row=>row.patientId===patientId);
  return `<div class="back"><a href="#pacientes/${patientId}">← ${esc(patient.name||patient.code)}</a></div>${header('REAVALIAÇÃO',`Evolução funcional · ${esc(patient.name||patient.code)}`,'Inicial × atual, usando apenas valores registrados.')}<section class="panel"><div class="reassessment-grid">${rows.length?rows.map(row=>`<article><span>${esc(row.label)}</span><div><small>Inicial</small><strong>${row.initial}${esc(row.unit)}</strong></div><b>→</b><div><small>Atual</small><strong>${row.current}${esc(row.unit)}</strong></div><em>${row.change==null?'—':`${row.change>0?'+':''}${Math.round(row.change*100)/100}${esc(row.unit)}`}</em></article>`).join(''):empty('Dados insuficientes','Registre ao menos duas medições comparáveis.')}</div></section>
  <section class="panel"><div class="section-title"><h2>Objetivos acompanhados</h2></div><form id="goal-form"><input type="hidden" name="patientId" value="${patientId}"><div class="form-grid">${field('Descrição *','description','text','','required')}${select('Categoria','category',[['Função','Função'],['Dor','Dor'],['ADM','ADM'],['Força','Força'],['Equilíbrio','Equilíbrio'],['Marcha','Marcha'],['Participação','Participação']])}${field('Data','date','date',new Date().toLocaleDateString('sv-SE'))}${field('Prazo','deadline','date')}${select('Status','status',[['não iniciado','Não iniciado'],['em progresso','Em progresso'],['atingido','Atingido'],['parcialmente atingido','Parcialmente atingido'],['suspenso','Suspenso']])}${field('Medida relacionada','measure')}</div>${area('Observações','notes')}<button class="button primary" type="submit">Adicionar objetivo</button></form>${goals.length?`<div class="history-cards">${goals.map(goal=>`<article><span>${esc(goal.status)}</span><strong>${esc(goal.description)}</strong><small>${esc([goal.measure,goal.deadline&&`prazo ${date(goal.deadline)}`].filter(Boolean).join(' · '))}</small></article>`).join('')}</div>`:''}</section>`;
}

export function dischargePage(state,patientId=''){
  if(!patientId)return `${header('ENCERRAMENTO','Alta fisioterapêutica','Relatório editável sem completar informações ausentes.')}${patientNav(state,'alta','')}`;
  const patient=state.patients.find(row=>row.id===patientId),rows=state.discharges.filter(row=>row.patientId===patientId);if(!patient)return empty('Paciente não encontrado','');
  return `<div class="back"><a href="#pacientes/${patientId}">← ${esc(patient.name||patient.code)}</a></div>${header('ALTA','Registrar alta','Revise cada campo e o relatório antes de salvar ou imprimir.')}<section class="panel"><form id="discharge-form"><input type="hidden" name="patientId" value="${patientId}"><div class="form-grid">${field('Data *','date','date',new Date().toLocaleDateString('sv-SE'),'required')}${field('Motivo da alta','reason')}</div>${area('Condição inicial','initialCondition')}${area('Condição atual','currentCondition')}${area('Objetivos atingidos','achieved')}${area('Parcialmente atingidos','partial')}${area('Não atingidos','notAchieved')}${area('Resultados iniciais','initialResults')}${area('Resultados finais','finalResults')}${area('Orientações','guidance')}${area('Exercícios domiciliares','homeExercises')}${area('Necessidade de acompanhamento','followUp')}${area('Observações','notes')}${area('Relatório editável','report','','Gerar pelos campos preenchidos e revisar')}<div class="section-actions"><button type="button" class="button secondary" data-action="generate-discharge">Gerar relatório</button><button class="button primary" type="submit">Salvar alta</button></div></form></section>${rows.map(row=>`<section class="panel print-page"><h2>Relatório de alta · ${date(row.date)}</h2><p class="pre-line">${esc(row.report)}</p><button class="button ghost" data-action="print-page">Imprimir / PDF</button></section>`).join('')}`;
}

export function functionalModelPage(state,patientId=''){
  if(!patientId)return `${header('CIF / RACIOCÍNIO','Modelo funcional','Conecte achados, atividade, participação, objetivos e reavaliação.')}${patientNav(state,'modelo-funcional','')}`;
  const latest=state.functionalModels.filter(row=>row.patientId===patientId).at(-1)||{};
  return `<div class="back"><a href="#pacientes/${patientId}">← Paciente</a></div>${header('MODELO FUNCIONAL','CIF simplificada e raciocínio estruturado','O usuário registra as relações; o aplicativo não gera diagnóstico ou prescrição.')}<section class="panel"><form id="functional-model-form"><input type="hidden" name="patientId" value="${patientId}">${area('Funções e estruturas corporais','bodyFunctions',latest.bodyFunctions)}${area('Atividade','activity',latest.activity)}${area('Participação','participation',latest.participation)}${area('Fatores ambientais','environment',latest.environment)}${area('Fatores pessoais pertinentes','personal',latest.personal)}<hr>${area('Achados','findings',latest.findings)}${area('Problemas','problems',latest.problems)}${area('Problema funcional principal','mainProblem',latest.mainProblem)}${area('Hipóteses a discutir','hypotheses',latest.hypotheses)}${area('Objetivo do paciente','patientGoal',latest.patientGoal)}${area('Objetivos terapêuticos','therapyGoals',latest.therapyGoals)}${area('Medidas de resultado','outcomes',latest.outcomes)}${area('Possibilidades de intervenção','interventions',latest.interventions)}${area('Critérios de progressão','progression',latest.progression)}${area('Critérios de regressão','regression',latest.regression)}${area('Reavaliação','reassessment',latest.reassessment)}<button class="button primary" type="submit">Salvar modelo funcional</button></form></section><section class="functional-flow"><span>Achado</span><b>↓</b><span>Problema funcional</span><b>↓</b><span>Atividade</span><b>↓</b><span>Participação</span><b>↓</b><span>Objetivo</span><b>↓</b><span>Medida</span><b>↓</b><span>Intervenção</span><b>↓</b><span>Reavaliação</span></section>`;
}

export function neuroPage(state,patientId=''){
  if(!patientId)return `${header('AVALIAÇÃO ESPECÍFICA','Neuro Adulto','Registro funcional próprio, separado da avaliação musculoesquelética.')}${patientNav(state,'neuro','')}`;
  const rows=state.neuroAssessments.filter(row=>row.patientId===patientId);
  return `<div class="back"><a href="#pacientes/${patientId}">← Paciente</a></div>${header('NEURO ADULTO','Avaliação neurológica funcional','Preencha apenas o avaliado e registre lado, segmento, assistência e contexto.')}<section class="panel"><form id="neuro-assessment-form"><input type="hidden" name="patientId" value="${patientId}"><div class="form-grid">${field('Data *','date','date',new Date().toLocaleDateString('sv-SE'),'required')}${select('Contexto','context',neuroContexts.map(value=>[value,value]))}</div>${['Estado geral','Consciência/orientação','Comunicação','Sensibilidade superficial/profunda/propriocepção','Tônus — lado e segmento','Reflexos avaliados','Força muscular 0–5','Coordenação','Controle de tronco','Transferências','Sedestação','Ortostatismo','Equilíbrio','Marcha','Dispositivo auxiliar','Assistência necessária','MMSS','MMII','Função manual','Observações funcionais'].map(label=>area(label,label.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+(.)/g,(_,char)=>char.toUpperCase()).replace(/^[A-Z]/,char=>char.toLowerCase()))).join('')}<button class="button primary" type="submit">Salvar avaliação Neuro</button></form></section>${rows.length?`<section class="panel"><h2>Histórico Neuro</h2>${rows.map(row=>`<article class="entry"><strong>${date(row.date)} · ${esc(row.context)}</strong><p>${esc(row.observacoesFuncionais||row.marcha||row.controleDeTronco||'Registro salvo')}</p></article>`).join('')}</section>`:''}`;
}

export function pediatricsPage(state,patientId=''){
  if(!patientId)return `${header('AVALIAÇÃO ESPECÍFICA','Pediatria','Desenvolvimento, participação, brincadeira e família em estrutura própria.')}${patientNav(state,'pediatria','')}`;
  return `<div class="back"><a href="#pacientes/${patientId}">← Paciente</a></div>${header('PEDIATRIA','Avaliação pediátrica','Não apresenta reflexos ou marcos como diagnóstico automático.')}<section class="panel"><form id="pediatric-assessment-form"><input type="hidden" name="patientId" value="${patientId}"><div class="form-grid">${field('Data *','date','date',new Date().toLocaleDateString('sv-SE'),'required')}${field('Idade cronológica','chronologicalAge')}${field('Idade corrigida, se aplicável','correctedAge')}${field('Diagnóstico informado','reportedDiagnosis')}</div>${area('Queixa','complaint')}${area('Objetivo familiar','familyGoal')}${area('História do desenvolvimento','developmentHistory')}${area('Controle motor — cefálico, tronco, rolamento e transições','motorControl')}${area('Sedestação, quatro apoios, engatinhar e ajoelhar','floorMobility')}${area('Ortostatismo e marcha','standingGait')}${area('Equilíbrio e coordenação','balanceCoordination')}${area('Motricidade grossa','grossMotor')}${area('Alcance e manipulação','reachHandling')}${area('Brincadeira e participação','playParticipation')}${area('Família/cuidadores','caregivers')}${area('Reflexos e reações observados','reflexesReactions')}${area('Observações','notes')}<button class="button primary" type="submit">Salvar avaliação pediátrica</button></form></section><section class="panel"><h2>Atividades lúdicas para organizar</h2><div class="functional-test-grid">${pediatricActivities.map(item=>`<article class="reference-card"><h3>${esc(item.name)}</h3><p><b>Objetivo:</b> ${esc(item.objective)}</p><p><b>Como realizar:</b> ${esc(item.execution)}</p><p><b>Progressão:</b> ${esc(item.progression)}</p><p><b>Regressão:</b> ${esc(item.regression)}</p><small>${esc(item.care)}</small></article>`).join('')}</div></section>`;
}

export function homeProgramPage(state,exercises,patientId=''){
  if(!patientId)return `${header('ORIENTAÇÃO','Programa domiciliar','Selecione exercícios e ajuste todas as instruções antes de entregar.')}${patientNav(state,'domiciliar','')}`;
  const programs=state.homePrograms.filter(row=>row.patientId===patientId);
  return `<div class="back"><a href="#pacientes/${patientId}">← Paciente</a></div>${header('PROGRAMA DOMICILIAR','Criar orientação','Nenhuma dose ou progressão é aplicada automaticamente.')}<section class="panel"><form id="home-program-form"><input type="hidden" name="patientId" value="${patientId}"><div class="form-grid">${field('Data *','date','date',new Date().toLocaleDateString('sv-SE'),'required')}${field('Título','title','text','Programa domiciliar')}</div><label class="field"><span>Exercícios *</span><select name="exerciseIds" multiple size="8" required>${exercises.map(item=>`<option value="${item.id}">${esc(item.name)}</option>`).join('')}</select></label><div class="form-grid">${field('Séries','sets')}${field('Repetições','reps')}${field('Duração','duration')}${field('Frequência','frequency')}</div>${area('Instruções','instructions')}${area('Cuidados','care')}${area('Observações','notes')}<button class="button primary" type="submit">Salvar programa</button></form></section>${programs.map(row=>`<section class="panel print-page"><h2>${esc(row.title)} · ${date(row.date)}</h2>${row.items.map(item=>`<article class="home-exercise"><strong>${esc(item.name)}</strong><p>${esc([row.sets&&`${row.sets} séries`,row.reps&&`${row.reps} repetições`,row.duration,row.frequency].filter(Boolean).join(' · '))}</p></article>`).join('')}<p class="pre-line">${esc(row.instructions)}</p><p><b>Cuidados:</b> ${esc(row.care)}</p><button class="button ghost" data-action="print-page">Imprimir / PDF</button></section>`).join('')}`;
}

export function toolsPage(){
  return `${header('USO RÁPIDO','Ferramentas','Cronômetro, temporizador, metrônomo e contadores sem sair do fluxo clínico.')}<div class="tools-grid"><section class="panel tool-card"><h2>Cronômetro</h2><strong id="tool-stopwatch">00:00.00</strong><div class="section-actions"><button class="button primary" data-action="tool-start">Iniciar</button><button class="button secondary" data-action="tool-pause">Pausar</button><button class="button ghost" data-action="tool-lap">Volta</button><button class="button ghost" data-action="tool-reset">Zerar</button></div><ol id="tool-laps"></ol></section><section class="panel tool-card"><h2>Temporizador</h2><div class="quick-prompts"><button data-action="timer-preset" data-seconds="30">30 s</button><button data-action="timer-preset" data-seconds="60">60 s</button><button data-action="timer-preset" data-seconds="120">2 min</button></div>${field('Personalizado (segundos)','timerSeconds','number','30','min="1" max="3600"')}<strong id="tool-countdown">00:30</strong><button class="button primary" data-action="timer-start">Iniciar</button></section><section class="panel tool-card"><h2>Metrônomo</h2>${field('BPM','metronomeBpm','number','80','min="30" max="240"')}<strong id="metronome-beat">●</strong><button class="button primary" data-action="metronome-toggle">Iniciar / parar</button></section><section class="panel tool-card"><h2>Contadores</h2><div class="manual-counters"><div><span>Repetições</span><strong id="manual-reps">0</strong><button class="button primary" data-action="count-rep">＋ repetição</button></div><div><span>Voltas</span><strong id="manual-laps">0</strong><button class="button secondary" data-action="count-lap">＋ volta</button></div></div><button class="button ghost" data-action="count-reset">Zerar contadores</button></section></div>`;
}

export function morePage(){
  const links=[['testes-funcionais','Testes funcionais','Aplicar, cronometrar e acompanhar resultados'],['reavaliacao','Reavaliação','Comparar avaliação inicial e atual'],['alta','Alta','Registrar e imprimir relatório editável'],['modelo-funcional','CIF / modelo funcional','Organizar funcionalidade e raciocínio'],['neuro','Neuro Adulto','Avaliação neurológica própria'],['pediatria','Pediatria','Avaliação e atividades lúdicas'],['domiciliar','Programa domiciliar','Selecionar exercícios e imprimir'],['ferramentas','Ferramentas rápidas','Cronômetro, metrônomo e contadores'],['casos','Discussão de caso','Organizar apresentação ao preceptor'],['dados','Dados e privacidade','Backup e controle local']];
  return `${header('FISIO CLÍNICO 0.6','Mais recursos','Acesso direto aos fluxos clínicos e ferramentas.')}<div class="more-grid">${links.map(([route,title,text])=>`<a class="reference-card" href="#${route}"><h3>${title}</h3><p>${text}</p><b>→</b></a>`).join('')}</div>`;
}
