export const functionalTests=[
  {id:'tug',name:'Timed Up and Go — TUG',objective:'Registrar o tempo e a qualidade da mobilidade funcional ao levantar, caminhar, virar e sentar.',context:'Pessoas com limitação de mobilidade, quando o protocolo for pertinente.',materials:'Cadeira, marcação de percurso e cronômetro.',preparation:'Registrar calçado, dispositivo, assistência e percurso conforme protocolo adotado.',execution:'Ao comando, levantar, caminhar até a marca, virar, retornar e sentar. Registrar adaptações e segurança.',variable:'Tempo',unit:'s',timed:true,limitations:'O resultado depende do protocolo, ambiente, dispositivo e população. Não aplicar ponto de corte sem referência específica.',source:'CDC STEADI e Rehabilitation Measures Database (Shirley Ryan AbilityLab).'},
  {id:'10mwt',name:'10 Meter Walk Test — 10MWT',objective:'Registrar velocidade de marcha em condição definida.',context:'Avaliação longitudinal da velocidade de marcha.',materials:'Percurso medido e cronômetro.',preparation:'Definir trecho cronometrado, aceleração/desaceleração, velocidade solicitada e dispositivo.',execution:'Cronometrar o trecho definido e registrar distância, tempo, assistência e condições.',variable:'Tempo e/ou velocidade',unit:'s',timed:true,derived:'speed',limitations:'Protocolos variam; compare apenas condições equivalentes.',source:'Rehabilitation Measures Database (Shirley Ryan AbilityLab).'},
  {id:'5xsts',name:'5 Times Sit-to-Stand — 5xSTS',objective:'Registrar desempenho ao levantar e sentar cinco vezes.',context:'Mobilidade funcional e desempenho de membros inferiores.',materials:'Cadeira estável e cronômetro.',preparation:'Registrar altura da cadeira, uso dos braços, assistência e dispositivo.',execution:'Cronometrar cinco ciclos completos conforme protocolo selecionado.',variable:'Tempo',unit:'s',timed:true,limitations:'Altura da cadeira, estratégia e uso dos braços influenciam o resultado.',source:'Rehabilitation Measures Database (Shirley Ryan AbilityLab).'},
  {id:'30cst',name:'30-Second Chair Stand',objective:'Registrar o número de ciclos de sentar e levantar em 30 segundos.',context:'Desempenho funcional de membros inferiores.',materials:'Cadeira estável e cronômetro.',preparation:'Registrar altura, uso dos braços, assistência e critérios de interrupção.',execution:'Contar ciclos completos durante 30 segundos conforme protocolo.',variable:'Repetições',unit:'repetições',timerSeconds:30,limitations:'Não substituir protocolo completo; registrar adaptações.',source:'CDC STEADI.'},
  {id:'2mwt',name:'2 Minute Walk Test — 2MWT',objective:'Registrar distância caminhada em dois minutos.',context:'Tolerância à caminhada quando uma medida curta for mais apropriada.',materials:'Percurso medido, cronômetro e contador de voltas.',preparation:'Registrar percurso, dispositivo, assistência, pausas e monitoramento.',execution:'Registrar distância total, pausas e sintomas durante dois minutos.',variable:'Distância',unit:'m',timerSeconds:120,limitations:'Percurso, comandos e pausas afetam comparabilidade.',source:'Rehabilitation Measures Database (Shirley Ryan AbilityLab).'},
  {id:'6mwt',name:'6 Minute Walk Test — 6MWT',objective:'Registrar distância caminhada em seis minutos sob protocolo definido.',context:'Capacidade funcional de caminhada quando houver triagem e estrutura adequadas.',materials:'Percurso padronizado, cronômetro, contador de voltas e monitoramento pertinente.',preparation:'Realizar triagem de segurança e seguir protocolo institucional completo.',execution:'Registrar distância, pausas, dispositivo, assistência, sintomas e motivo de interrupção.',variable:'Distância',unit:'m',timerSeconds:360,limitations:'Exige protocolo, percurso, comandos e segurança padronizados.',source:'American Thoracic Society e Rehabilitation Measures Database.'},
  {id:'four-stage',name:'Four Stage Balance Test',objective:'Registrar a manutenção de quatro posições de equilíbrio estático.',context:'Triagem funcional de equilíbrio quando apropriada.',materials:'Cronômetro e apoio próximo para segurança.',preparation:'Definir assistência e interromper se a condição não for segura.',execution:'Aplicar as posições na ordem do protocolo e registrar tempo/posição alcançada.',variable:'Tempo/posição',unit:'s',timed:true,limitations:'Não interpretar isoladamente; documentar assistência e interrupção.',source:'CDC STEADI.'},
  {id:'single-leg',name:'Apoio unipodal',objective:'Registrar tempo de apoio em um membro em condição definida.',context:'Observação longitudinal de equilíbrio estático.',materials:'Cronômetro e apoio próximo.',preparation:'Definir lado, calçado, superfície, visão e assistência.',execution:'Cronometrar enquanto os critérios definidos forem mantidos; registrar tentativas.',variable:'Tempo',unit:'s',timed:true,side:true,limitations:'Condições precisam ser repetidas para comparação.',source:'Registro clínico estruturado; usar protocolo institucional quando disponível.'},
  {id:'tandem',name:'Tandem',objective:'Registrar manutenção ou execução da posição/marcha tandem.',context:'Observação de equilíbrio em base reduzida.',materials:'Cronômetro ou percurso e apoio próximo.',preparation:'Definir estático/dinâmico, lado à frente e assistência.',execution:'Registrar tempo, distância ou passos conforme tarefa definida.',variable:'Tempo/distância/passos',unit:'s',timed:true,side:true,limitations:'Descrever exatamente a tarefa; não há interpretação automática.',source:'Registro clínico estruturado; usar protocolo institucional quando disponível.'}
];

export const neuroContexts=['AVE','Parkinson','Lesão medular','Traumatismo cranioencefálico','Doença neurológica','Outro'];
export const neuroPositions=['Decúbito','Sedestação','Quatro apoios','Ajoelhado','Ortostatismo','Marcha'];
export const pediatricActivities=[
  ['Alcance de brinquedo','Alcance, controle postural e exploração','Adequar posição e distância ao desenvolvimento e interesse; oferecer tempo para iniciativa.'],
  ['Circuito lúdico','Transições, mobilidade e planejamento motor','Usar obstáculos seguros, simples e supervisionados; adaptar altura e sequência.'],
  ['Transferência de peso com bola','Controle de tronco e equilíbrio','Mover a bola em direções toleradas, mantendo apoio e interação.'],
  ['Mudança de posição','Variabilidade motora e transições','Facilitar apenas o necessário e permitir participação ativa.'],
  ['Interação bilateral','Uso coordenado dos membros','Escolher brinquedo apropriado, sem impor padrão rígido ou dose universal.']
].map(([name,objective,execution],index)=>({id:`ped-${index+1}`,name,objective,execution,progression:'Aumentar desafio da tarefa ou reduzir ajuda conforme resposta.',regression:'Simplificar ambiente, amplitude ou oferecer mais apoio.',care:'Respeitar sinais de fadiga, comunicação, interesse, segurança e orientação do cuidador.'}));
